import {AnalysisReport,Match,Mission,Signal} from './types';
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
export function analyseMatch(match:Match,recent:Match[]):AnalysisReport{
 const last5=recent.slice(0,5); const recentCs=avg(last5.map(m=>m.metrics.csPerMin)); const recentDeaths=avg(last5.map(m=>m.deaths));
 const farmingSeverity=Math.max(0,Math.min(1,(6.5-Math.min(match.metrics.csPerMin,recentCs))/2.4));
 const deathSeverity=Math.max(0,Math.min(1,(Math.max(match.deaths,recentDeaths)-4)/5));
 let primary:Signal;
 if(farmingSeverity>=deathSeverity){primary={category:'RESOURCE_COLLECTION',severity:+farmingSeverity.toFixed(2),confidence:last5.length>=3?.82:.64,facts:[`This match: ${match.metrics.csPerMin.toFixed(1)} CS/min.`,`Recent 5 average: ${recentCs.toFixed(1)} CS/min.`],inference:'Your economy is likely being limited by resource collection, especially once the map opens up.',suggestion:'Before grouping after recall, identify the safest available wave and collect it when the game state allows.'};}
 else {primary={category:'DEATHS',severity:+deathSeverity.toFixed(2),confidence:last5.length>=3?.79:.62,facts:[`This match: ${match.deaths} deaths.`,`Recent 5 average: ${recentDeaths.toFixed(1)} deaths.`],inference:'Repeated deaths are likely removing too many farming and fighting windows.',suggestion:'For the next games, avoid entering fights until you can name the main enemy threat to you.'};}
 const mission:Mission=primary.category==='DEATHS'?{id:`m-${Date.now()}`,category:'DEATHS',title:'SURVIVAL DISCIPLINE',metric:'deaths',target:4,unit:'deaths or fewer',gamesRequired:3,gamesCompleted:0,successfulGames:0,rules:['Name the biggest threat before each major fight.','Do not face-check without information.','If key defensive cooldowns are down, give space.'],status:'DISCOVER',createdAt:new Date().toISOString()}:{id:`m-${Date.now()}`,category:'RESOURCE_COLLECTION',title:'RESOURCE DISCIPLINE',metric:'csPerMin',target:6.5,unit:'CS/min',gamesRequired:3,gamesCompleted:0,successfulGames:0,rules:['Check both side waves after recall.','Do not automatically walk mid after lane.','Take safe resources before objectives.'],status:'DISCOVER',createdAt:new Date().toISOString()};
 const good=[match.deaths<=4?'You kept deaths under control.':'You still contributed despite a difficult game.',match.kills+match.assists>=10?'You contributed to a high number of takedowns.':'You stayed involved in key moments.',match.metrics.csPerMin>=recentCs?'Your farming pace beat your recent average.':'You created a clear baseline to improve next game.'].slice(0,3);
 return {matchId:match.id,performance:Math.max(1,Math.min(10,+((match.result==='WIN'?1:0)+5.4+(match.metrics.csPerMin-5.5)*.55-(match.deaths-5)*.18).toFixed(1))),good,primary,mission,summary:`${primary.category==='RESOURCE_COLLECTION'?'Resource collection':'Survival'} is the clearest next focus. Keep the mission stable for 3 relevant games before changing it.`};
}
export function missionResult(mission:Mission,match:Match){const value=mission.metric==='deaths'?match.deaths:match.metrics.csPerMin;const pass=mission.metric==='deaths'?value<=mission.target:value>=mission.target;return {value,pass};}
export function climbScore(matches:Match[]){if(!matches.length)return 0;const last=matches.slice(0,10);const cs=Math.min(100,avg(last.map(m=>m.metrics.csPerMin))/7*100);const deaths=Math.max(0,100-(avg(last.map(m=>m.deaths))-2)*13);const consistency=Math.max(0,100-(Math.max(...last.map(m=>m.metrics.csPerMin))-Math.min(...last.map(m=>m.metrics.csPerMin)))*17);return Math.round(cs*.38+deaths*.34+consistency*.28);}
