create extension if not exists "pgcrypto";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, game_name text, tagline text, region text, role text, rank text, champions jsonb default '[]'::jsonb, frustration text, is_founder boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.riot_accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, puuid text, game_name text not null, tagline text not null, region text not null, created_at timestamptz default now(), unique(user_id,game_name,tagline,region));
create table if not exists public.matches (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, external_match_id text, champion text not null, role text not null, result text not null check(result in('WIN','LOSS')), kills int not null default 0, deaths int not null default 0, assists int not null default 0, duration_seconds int not null, rank text, source text not null check(source in('manual','screenshot','riot','demo')), occurred_at timestamptz, created_at timestamptz default now());
create table if not exists public.match_metrics (id uuid primary key default gen_random_uuid(), match_id uuid not null unique references public.matches(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, cs int, cs_per_min numeric, gold_per_min numeric, damage_per_min numeric, kill_participation numeric, vision_score numeric, farm_after_15 numeric, objective_participation numeric, raw jsonb default '{}'::jsonb);
create table if not exists public.analysis_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, match_id uuid not null references public.matches(id) on delete cascade, primary_issue text not null, severity numeric not null, confidence numeric not null, facts jsonb not null default '[]'::jsonb, inference text, suggestion text, structured_output jsonb not null default '{}'::jsonb, useful boolean, feedback_reason text, created_at timestamptz default now());
create table if not exists public.missions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, category text not null, title text not null, metric text not null, target numeric not null, unit text not null, games_required int not null default 3, status text not null default 'DISCOVER', rules jsonb default '[]'::jsonb, active boolean default true, created_at timestamptz default now(), mastered_at timestamptz);
create table if not exists public.mission_progress (id uuid primary key default gen_random_uuid(), mission_id uuid not null references public.missions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, match_id uuid references public.matches(id) on delete set null, metric_value numeric, passed boolean not null default false, created_at timestamptz default now());
create table if not exists public.improvement_scores (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, total int not null check(total between 0 and 100), categories jsonb not null default '{}'::jsonb, calculated_at timestamptz default now());
create table if not exists public.weekly_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, period_start date not null, period_end date not null, payload jsonb not null, created_at timestamptz default now());
create table if not exists public.uploads (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, storage_path text not null, media_type text not null, status text not null default 'uploaded', extracted jsonb, confirmed jsonb, created_at timestamptz default now());
create table if not exists public.coach_messages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in('user','assistant')), content text not null, grounding jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, stripe_customer_id text, stripe_subscription_id text, plan text not null default 'FREE', status text, trial_end timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.founder_users (user_id uuid primary key references auth.users(id) on delete cascade, cohort int default 1, pro_until timestamptz, founder_price_id text, created_at timestamptz default now());
create table if not exists public.feedback (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, analysis_id uuid references public.analysis_reports(id) on delete cascade, useful boolean not null, reason text, details text, created_at timestamptz default now());
create table if not exists public.api_usage (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, kind text not null, units numeric not null default 1, estimated_cost numeric default 0, created_at timestamptz default now());
create table if not exists public.feature_flags (key text primary key, enabled boolean not null default false, config jsonb default '{}'::jsonb, updated_at timestamptz default now());
create table if not exists public.admin_notes (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, note text not null, created_at timestamptz default now());
create table if not exists public.achievements (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text not null, xp int not null default 0);
create table if not exists public.user_achievements (user_id uuid references auth.users(id) on delete cascade, achievement_id uuid references public.achievements(id) on delete cascade, earned_at timestamptz default now(), primary key(user_id,achievement_id));
create table if not exists public.champion_stats (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, champion text not null, role text, games int default 0, wins int default 0, metrics jsonb default '{}'::jsonb, updated_at timestamptz default now(), unique(user_id,champion,role));
create table if not exists public.vod_reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, upload_id uuid references public.uploads(id) on delete set null, focus text, result jsonb, credits_used numeric default 0, created_at timestamptz default now());

alter table public.profiles enable row level security; alter table public.riot_accounts enable row level security; alter table public.matches enable row level security; alter table public.match_metrics enable row level security; alter table public.analysis_reports enable row level security; alter table public.missions enable row level security; alter table public.mission_progress enable row level security; alter table public.improvement_scores enable row level security; alter table public.weekly_reports enable row level security; alter table public.uploads enable row level security; alter table public.coach_messages enable row level security; alter table public.subscriptions enable row level security; alter table public.feedback enable row level security; alter table public.api_usage enable row level security; alter table public.champion_stats enable row level security; alter table public.vod_reviews enable row level security;

do $$ declare t text; begin foreach t in array array['profiles','riot_accounts','matches','match_metrics','analysis_reports','missions','mission_progress','improvement_scores','weekly_reports','uploads','coach_messages','subscriptions','feedback','api_usage','champion_stats','vod_reviews'] loop execute format('create policy %I on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)', 'own_'||t,t); end loop; end $$;
insert into public.feature_flags(key,enabled,config) values ('RIOT_API_ENABLED',false,'{}'::jsonb) on conflict(key) do nothing;
