'use client';
import {useMemo,useState} from 'react';import {AppShell} from '@/components/AppShell';import {PageHead} from '@/components/UI';import {useAccount,matchesFor,missionFor} from '@/components/AccountContext';
type Msg={who:'user'|'ai';text:string};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
function buildReply(q:string,active:any,matches:any[],mission:any){const s=q.toLowerCase();const recent=matches.slice(0,5);const cs=avg(recent.map(m=>m.metrics.csPerMin));const post=avg(recent.map(m=>m.metrics.post15CsPerMin||m.metrics.csPerMin));const lane=avg(recent.map(m=>m.metrics.laneCsPerMin||m.metrics.csPerMin));const d=avg(recent.map(m=>m.deaths));const kp=avg(recent.map(m=>m.metrics.killParticipation||0));const g15=avg(recent.map(m=>m.metrics.goldDiffAt15||0));
if(/complete|done|finished|mastered/.test(s))return `I won't mark ${mission.title} complete from chat. The pass condition is ${mission.target} ${mission.unit} across ${mission.gamesRequired} relevant games. Your next analysed match has to prove it. That prevents the Coach from rewarding intention instead of behaviour.`;
if(/plat|platinum|rank|climb/.test(s))return `${active.gameName} is ${active.rank}. In this account's recent five, full-game farm is ${cs.toFixed(1)} CS/min, lane pace ${lane.toFixed(1)}, post-15 pace ${post.toFixed(1)}, deaths ${d.toFixed(1)}, KP ${Math.round(kp*100)}%, and average gold diff @15 ${g15>=0?'+':''}${Math.round(g15)}. ${active.role==='ADC'?`The clearest gap is the ${Math.abs(lane-post).toFixed(1)} CS/min drop after lane. For an ADC trying to climb, I would first make post-lane resource access repeatable without increasing post-20 deaths. Then reassess teamfight survival.`:`For jungle, I would prioritise objective setup and recall tempo before chasing more kills. A jungler can have acceptable KDA and still arrive late to dragon/Herald windows.`}`;
if(/last five|last 5|compare|recent/.test(s))return `Last five on ${active.gameName}${active.tagline}: ${recent.filter(m=>m.result==='WIN').length}-${recent.filter(m=>m.result==='LOSS').length}, ${cs.toFixed(1)} CS/min, ${d.toFixed(1)} deaths, ${Math.round(kp*100)}% KP. ${active.role==='ADC'?`Lane farm averages ${lane.toFixed(1)} but post-15 is ${post.toFixed(1)}. That split matters more than the headline KDA because it tells us *when* your economy stops scaling.`:'I would compare objective participation, first major recall timing and whether deaths happen before neutral objectives rather than just total CS.'}`;
if(/kog|kog'maw/.test(s))return `On Kog'Maw, your coaching problem should be framed around access to safe gold and uninterrupted DPS windows, not “play safer” in general. From this sample, the stronger signal is economy after lane. The next useful Kog review would ask: did you reach first/second item on time, did you give up catchable waves to group early, and did you die after 20 before your frontline/peel could establish the fight? I would not invent matchup-specific spell timings without current matchup data.`;
if(/aphelios/.test(s))return `For Aphelios, scoreboard metrics alone cannot tell me whether you managed weapon order correctly, so I won't pretend they can. What I can track reliably from match/timeline data is CS@10/15, gold and XP @15, item breakpoints, death timings, KP and damage share. A clip can then add gun cycle, spacing and target-access evidence.`;
if(/cs|farm|wave|side lane|after lane|economy/.test(s))return `FACT: recent lane pace is ${lane.toFixed(1)} CS/min and post-15 pace is ${post.toFixed(1)}. INFERENCE: this is more consistent with losing wave access after lane than basic last-hitting. NEXT RULE: after each recall post-15, check objective timer → identify the safest next wave → then decide whether to group. If an objective is spawning soon, setup can correctly override the wave. The mission is not “always side lane”.`;
if(/position|teamfight|fight|spacing|death/.test(s))return `Your recent death average is ${d.toFixed(1)}. To make positioning League-specific, I would split deaths by phase and by threat. Pre-10 deaths usually point toward lane trading/gank respect; post-20 deaths have much higher objective cost. Before a major fight, identify the enemy champion or spell that can actually start on you, then position outside that reliable threat range until it is committed. A scoreboard cannot prove a spacing error; a clip can.`;
if(/item|build|breakpoint/.test(s))return `For this account I would track *timing* before arguing about item choice: first completed item, second item, and whether those timings are slipping because post-lane CS falls. Build advice should be contextual to champion, enemy threats and patch data. The demo currently shows item names, but production recommendations should come from current legitimate static/patch data rather than hard-coded certainty.`;
if(/objective|dragon|baron|herald/.test(s))return active.role==='JUNGLE'?`For jungle, “objective participation” alone is too vague. The useful review is: were you on the correct side of the map 60–90 seconds before spawn, did you recall early enough to spend gold, did you show on a low-value camp/invade that surrendered setup, and did you know where the enemy jungler was likely to enter? Timeline data can support some of this; exact pathing intent needs more evidence.`:`For ADC, objective play starts with wave state and arrival timing. Catching a side wave can be correct when the objective is not contestable yet; catching it 20 seconds before Soul while your team loses river can be catastrophic. The Coach should judge the wave against the objective timer, not apply “farm more” blindly.`;
return `I can answer this account using tracked League evidence: rank, role, champion pool, CS@10/15, lane vs post-15 farm, gold/XP @15, item timing, death phase, KP, damage share and objective involvement where available. Ask about a specific champion, phase of game, item timing, objective, teamfight or your last five matches and I’ll keep fact separate from inference.`}
export default function Coach(){const {active}=useAccount();const matches=matchesFor(active.id);const mission=missionFor(active.id);const [q,setQ]=useState('');const [messages,setMessages]=useState<Msg[]>([{who:'ai',text:'Ask me about this Riot account. I will use League-specific evidence and tell you when the data cannot support a claim.'}]);const context=useMemo(()=>`${active.gameName}${active.tagline} · ${active.rank} · ${active.role}`,[active]);function send(t?:string){const text=(t??q).trim();if(!text)return;setMessages(m=>[...m,{who:'user',text},{who:'ai',text:buildReply(text,active,matches,mission)}]);setQ('')}return <AppShell><PageHead title="Coach" subtitle={context}/><div className="glass card" style={{marginBottom:14}}><div className="eyebrow">ACTIVE CLIMB CARD</div><h3>{mission.title}</h3><p className="muted">Pass: {mission.target} {mission.unit} · {mission.successfulGames}/{mission.gamesRequired} successful games</p></div><div className="glass card"><div className="chat">{messages.map((m,i)=><div className={`bubble ${m.who}`} key={i}>{m.text}</div>)}</div><div style={{display:'flex',gap:10,marginTop:18}}><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Why does my CS collapse after 15?"/><button className="btn primary" onClick={()=>send()}>SEND</button></div></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}>{['How do I get to Platinum?','Compare my last five games','Why does my CS drop after lane?',`What am I doing wrong on ${active.champions[0]}?`,'Are my deaths a positioning problem?','How should I think about objectives?'].map(x=><button className="btn secondary" key={x} onClick={()=>send(x)}>{x}</button>)}</div></AppShell>}
