'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {PageHead} from '@/components/UI';
import {useAccount,matchesFor} from '@/components/AccountContext';
import {useLearningPlan} from '@/components/LearningPlanContext';
import {ILPTask,IssueCategory} from '@/lib/types';
type Suggestion={title:string;category:IssueCategory;why:string;gameRule:string;metric:string;target:string;source:'COACH';priority?:number};type Msg={who:'user'|'ai';text:string;task?:Suggestion};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
function reply(q:string,active:any,matches:any[],tasks:ILPTask[]):{text:string;task?:Suggestion}{const s=q.toLowerCase(),r=matches.slice(0,5),cs=avg(r.map(m=>m.metrics.csPerMin)),post=avg(r.map(m=>m.metrics.post15CsPerMin||m.metrics.csPerMin)),lane=avg(r.map(m=>m.metrics.laneCsPerMin||m.metrics.csPerMin)),d=avg(r.map(m=>m.deaths)),postD=avg(r.map(m=>m.metrics.deathsPost20||0)),g15=avg(r.map(m=>m.metrics.goldDiffAt15||0));const activeFive=tasks.filter(t=>t.status!=='MASTERED'&&t.status!=='PAUSED').slice(0,5);const plan=activeFive.map((t,i)=>`${i+1}. ${t.title} — ${t.progress}% — ${t.status}`).join('\n');
 if(/learning plan|ilp|tasks|my plan/.test(s))return{text:`ADAPTIVE ILP — ${active.gameName}${active.tagline}\n${plan}\n\nThe plan is not static. Match evidence updates progress; mastered tasks leave the active five; Coach recommendations can add or replace a lower-priority task. I will not replace a task just because of one bad game unless the evidence is severe.`};
 if(/plat|platinum|climb|next rank/.test(s))return{text:`For ${active.rank} ${active.role}, recent five show ${cs.toFixed(1)} CS/min, lane ${lane.toFixed(1)}, post-15 ${post.toFixed(1)}, ${d.toFixed(1)} deaths and ${postD.toFixed(1)} post-20 deaths. The clearest repeatable gap is ${lane-post>0.5?`the ${Math.max(0,lane-post).toFixed(1)} CS/min post-lane drop`:'not a single economy collapse'}.

I would keep the ILP sequence narrow: economy/tempo → item timing → late-death control → objective setup → clip-based mechanics. If one reaches mastery evidence, the engine should promote the next priority rather than adding random advice.`};
 if(/cs|farm|wave|after lane|economy/.test(s)){const task:Suggestion={title:'Decide final wave 90s before objective',category:'TEMPO',why:'Your farm drop is most useful when linked to objective timing rather than “farm more at all costs”.',gameRule:'At 90 seconds before Dragon/Baron, choose your final wave and route to setup.',metric:'objectivePreparation',target:'3 reviewed correct setup decisions',source:'COACH',priority:84};return{text:`FACT: lane pace ${lane.toFixed(1)} → post-15 ${post.toFixed(1)} CS/min (${Math.max(0,lane-post).toFixed(1)} drop).\n\nINTERPRETATION: that pattern is more consistent with resource allocation/tempo than basic last-hitting.\n\nDECISION TREE:\n1. Check objective timer.\n2. Locate the safest wave.\n3. Ask if taking it makes you late to setup.\n4. If yes, rotate. If no, collect then move.\n5. Threat map overrides the CS target.\n\nThis can become an ILP task so future games are scored against the same decision.`,task};}
 if(/death|position|teamfight|spacing/.test(s)){const task:Suggestion={title:'Survive the first threat cycle',category:'TEAMFIGHTING',why:'Late ADC deaths are expensive, but scoreboard data alone cannot prove spacing.',gameRule:'Before sustained DPS range, identify the primary engage/assassin threat and wait until it is committed, blocked or covered by peel.',metric:'deathsPost20',target:'≤2 post-20 deaths in 3 of 5 games',source:'COACH',priority:90};return{text:`FACT: ${d.toFixed(1)} deaths/game recently; ${postD.toFixed(1)} occur after 20 in this demo sample.\n\nWHAT DATA SUPPORTS: death timing and frequency.\nWHAT NEEDS CLIP EVIDENCE: spacing, target selection, peel usage or whether the fight was already lost.\n\nFor each late death, tag the primary cause: engage, assassin flank, over-chase, isolated side lane, or doomed fight. If a clip is uploaded, the Coach can refine the ILP task instead of guessing.`,task};}
 if(/live|during game|watch me|follow game/.test(s))return{text:`LIVE MODE can follow permitted local League telemetry through the OVERPOWERED Companion, but it should not become an automated shotcaller. During a match it can silently track game time, exposed player stats and events, keep your pre-game ILP cue visible, then use the telemetry after the game to update your five tasks. Open Live Companion for the connection model.`};
 if(/kog/.test(s))return{text:`KOG'MAW DEVELOPMENT PLAN\n• Lane: preserve HP + CS; do not manufacture low-value trades without support setup.\n• Economy: protect post-15 farm because missed waves delay the sustained-DPS breakpoint.\n• Fight entry: front-to-back by default; identify engage/assassin threat before committing W uptime.\n• Side lane: short catch-and-rotate patterns, not deep solo pressure.\n• ILP evidence: economy from match data; positioning/target access from clip review.\n\nOpen Your Champions → Kog'Maw for the full rank plan.`};
 if(/build|rune|item/.test(s))return{text:`Build advice must be patch + role + rank + sample-size aware. OVERPOWERED should separate “current meta build” from “your execution of that build”. The useful coaching question is often not only which items are strongest, but whether your deaths/recalls/wave losses are delaying the item breakpoint.`};
 return{text:`I should tie advice back to your adaptive ILP, not just answer with generic League tips. Current active five:\n${plan}\n\nAsk about farm, late deaths, teamfights, objectives, item timings, a champion, live companion, or what should replace one of your five tasks.`}}
export default function Coach(){const {active}=useAccount();const matches=matchesFor(active.id);const {tasks,addTask}=useLearningPlan();const [q,setQ]=useState('');const [messages,setMessages]=useState<Msg[]>([{who:'ai',text:'I coach through your adaptive ILP. I use match evidence to reinforce, refine or propose one of your five development tasks.'}]);const context=useMemo(()=>`${active.gameName}${active.tagline} · ${active.rank} · ${active.role}`,[active]);function send(t?:string){const text=(t??q).trim();if(!text)return;const a=reply(text,active,matches,tasks);setMessages(m=>[...m,{who:'user',text},{who:'ai',text:a.text,task:a.task}]);setQ('')}return <AppShell><PageHead title="Coach + Adaptive ILP" subtitle={context} action={<div className="hero-actions"><Link href="/ilp" className="btn secondary">VIEW MY 5 TASKS</Link><Link href="/live" className="btn secondary">LIVE COMPANION</Link></div>}/><div className="coach-ilp-strip glass">{tasks.filter(t=>t.status!=='MASTERED'&&t.status!=='PAUSED').slice(0,5).map((t,i)=><div key={t.id}><span>0{i+1}</span><b>{t.title}</b><small>{t.progress}%</small></div>)}</div><div className="glass card" style={{marginTop:14}}><div className="chat">{messages.map((m,i)=><div key={i} className={`chat-wrap ${m.who}`}><div className={`bubble ${m.who}`}>{m.text}</div>{m.task&&<div className="coach-proposal glass"><div className="eyebrow">COACH → ADAPTIVE ILP PROPOSAL</div><b>{m.task.title}</b><p>{m.task.gameRule}</p><p className="muted">If your active five are full, OVERPOWERED pauses the lowest-priority task rather than creating an endless list.</p><button className="btn primary" onClick={()=>addTask(m.task!)}>ADD / ADAPT MY ILP</button></div>}</div>)}</div><div className="coach-input"><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="What should change in my plan after that game?"/><button className="btn primary" onClick={()=>send()}>SEND</button></div></div><div className="coach-prompts">{['Show my adaptive ILP','How do I get to Platinum?','Why does my CS drop after lane?','Are my late deaths a positioning problem?','Can Live Companion follow my game?',`Give me my ${active.champions[0]} plan`].map(x=><button className="btn secondary" key={x} onClick={()=>send(x)}>{x}</button>)}</div></AppShell>}
