import {describe,expect,it,vi} from 'vitest';
import {enforceCoachSuggestion,primaryAuthorityInstruction,resolveOwnedCoachAccount,type CoachAuthority} from '@/lib/server/coachAuthority';

const authority:CoachAuthority={accountId:'acct',role:null,latestPro:{},proMetric:{key:'reset_quality',score:42},memories:[],learningProfile:null,selectedRoleProfile:null,primary:{title:'Improve Reset Quality',category:'RECALL_TIMING',metric:'reset_quality',progress:42,target:'52+ PRO evidence score across 3 games',gameRule:'Spend before the next contested fight.',priority:95},tasks:[{title:'Improve Reset Quality',category:'RECALL_TIMING',metric:'reset_quality',progress:42,target:'52+ PRO evidence score across 3 games',gameRule:'Spend before the next contested fight.',priority:95},{title:'Improve Fight Selection',category:'TEAMFIGHTING',metric:'fight_selection',progress:55,target:'65+ PRO evidence score across 3 games',gameRule:'Only commit with a clear numbers or cooldown edge.',priority:90}]};

describe('Coach authority',()=>{
  it('suppresses a recommendation outside the active five',()=>{expect(enforceCoachSuggestion({title:'Farm more',category:'FARMING',metric:'csPerMin',gameRule:'Catch every wave',target:'7 CS/min',priority:99},authority)).toBeUndefined()});
  it('pins a primary recommendation to the persisted mission contract',()=>{expect(enforceCoachSuggestion({title:'Reset differently',category:'RECALL_TIMING',metric:'reset_quality',gameRule:'Different cue',target:'80',priority:50},authority)).toMatchObject({title:'Improve Reset Quality',metric:'reset_quality',category:'RECALL_TIMING',gameRule:'Spend before the next contested fight.',target:'52+ PRO evidence score across 3 games',priority:95})});
  it('allows a secondary Active Five mission without changing the primary',()=>{expect(enforceCoachSuggestion({title:'Take better fights',category:'TEAMFIGHTING',metric:'fight_selection',gameRule:'Different cue',target:'90',priority:99},authority)).toMatchObject({title:'Improve Fight Selection',metric:'fight_selection',category:'TEAMFIGHTING'});expect(authority.primary?.metric).toBe('reset_quality')});
  it('does not guess by category when two active missions share that category',()=>{const ambiguous={...authority,tasks:[...authority.tasks,{...authority.tasks[1],title:'Second fight mission',metric:'fight_conversion'}]};expect(enforceCoachSuggestion({title:'Generic fight',category:'TEAMFIGHTING',metric:'unknown',gameRule:'x',target:'x',priority:90},ambiguous)).toBeUndefined()});
  it('makes the primary semantic contract explicit',()=>{expect(primaryAuthorityInstruction(authority)).toContain('only current primary limiter');expect(primaryAuthorityInstruction(authority)).toContain('reset_quality')});
  it('accepts an explicitly selected account only when owned by the user',async()=>{const maybeSingle=vi.fn().mockResolvedValue({data:{id:'acct-2'},error:null});const eqId=vi.fn(()=>({maybeSingle}));const eqUser=vi.fn(()=>({eq:eqId}));const select=vi.fn(()=>({eq:eqUser}));const db={from:vi.fn(()=>({select}))};await expect(resolveOwnedCoachAccount(db,'user-1','acct-2')).resolves.toBe('acct-2');expect(eqUser).toHaveBeenCalledWith('id','acct-2')});
  it('rejects a selected account that is not owned by the user',async()=>{const maybeSingle=vi.fn().mockResolvedValue({data:null,error:null});const db={from:vi.fn(()=>({select:()=>({eq:()=>({eq:()=>({maybeSingle})})})}))};await expect(resolveOwnedCoachAccount(db,'user-1','other')).rejects.toThrow('selected Riot account')});
});
