import Link from 'next/link';
import {demoMission,demoMatches} from '@/data/demo';
import {MatchCard,MissionCard} from '@/components/UI';
export default function Landing(){return <><header className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center',paddingTop:24}}><div className="logo">CLIMB<span>//AI</span></div><div style={{display:'flex',gap:10}}><Link className="btn secondary" href="/login">LOG IN</Link><Link className="btn primary" href="/signup">START FREE</Link></div></header><main><section className="hero container"><div className="eyebrow">PLAY → ANALYSE → FIX ONE THING → REPEAT</div><h1>STOP MAKING<br/>THE SAME MISTAKE<br/>EVERY GAME.</h1><p>Your personal League improvement coach analyses your games, finds what is stopping you climbing, and gives you one thing to fix next.</p><div className="hero-actions"><Link className="btn primary" href="/signup">ANALYSE MY GAMES</Link><a className="btn secondary" href="#loop">SEE HOW IT WORKS</a></div><p className="muted" style={{fontSize:13}}>Built for players who want to improve — not just stare at statistics.</p><div className="glass mock"><div className="mock-grid"><MissionCard mission={demoMission}/><div className="grid"><div className="glass card"><div className="eyebrow">CURRENT PROBLEM</div><h2>Resource Collection</h2><div className="big-number">5.2 <span style={{fontSize:18}}>CS/min</span></div></div><div className="glass card"><div className="eyebrow">NEXT GAME TARGET</div><h2>6.0+ CS/min</h2><p className="muted">After every recall, identify the safest available wave before grouping mid.</p><div className="progress"><i style={{width:'87%'}}/></div></div></div></div></div></section>
<section className="section"><div className="container"><h2 className="section-title">Stats tell you what happened.<br/>CLIMB//AI tells you what to do next.</h2><div className="grid two"><div className="glass card"><div className="eyebrow">TRADITIONAL STATS SITE</div><h3>KDA · CS · Damage · Win rate · Items</h3><p className="muted">Useful information, but you still have to work out what matters and what to change.</p></div><div className="glass card"><div className="eyebrow">CLIMB//AI</div><h3>Biggest mistake · Why it matters · Specific fix · Next-game mission · Proof of improvement</h3><p className="muted">One clear feedback loop instead of a wall of numbers.</p></div></div></div></section>
<section className="section" id="loop"><div className="container"><div className="eyebrow">THE CLIMB LOOP</div><h2 className="section-title">One problem. One mission. Repetition until it sticks.</h2><div className="grid five">{['PLAY','ANALYSE','GET YOUR MISSION','PLAY AGAIN','LEVEL UP'].map((x,i)=><div className="glass card" key={x}><div className="eyebrow">0{i+1}</div><h3>{x}</h3></div>)}</div></div></section>
<section className="section"><div className="container"><div className="eyebrow">EXAMPLE AI REVIEW</div><h2 className="section-title">Evidence first. Advice second.</h2><MatchCard match={demoMatches[1]}/><div className="glass card" style={{marginTop:16}}><div className="eyebrow">AI COACH</div><div className="grid two"><div><h3 className="success">GOOD</h3><p className="muted">Your lane survival improved and you avoided unnecessary early deaths.</p><h3>BIGGEST LEAK</h3><p>Mid-game resource loss.</p></div><div><h3>WHY</h3><p className="muted">Your farming pace dropped after laning phase while you grouped mid repeatedly.</p><h3>NEXT GAME MISSION</h3><p>Reach 7 CS/min. Before walking mid after recall, check both side lanes.</p></div></div></div></div></section>
<section className="section"><div className="container"><h2 className="section-title">Built for every role.</h2><div className="grid five">{['ADC','Support','Mid','Jungle','Top'].map(x=><div className="glass card" key={x}><h3>{x}</h3><p className="muted">{x==='ADC'?'Enhanced coaching available':'Core improvement loop available'}</p></div>)}</div></div></section>
<section className="section"><div className="container"><h2 className="section-title">Simple pricing after value.</h2><div className="grid three">{[['FREE','£0','3 detailed AI reviews/week'],['PLUS','£9.99/mo','Advanced Climb Loop + 90-day analytics'],['PRO','£19.99/mo','Higher AI usage + video allowance']].map(([n,p,d])=><div className="glass card" key={n}><div className="eyebrow">{n}</div><div className="big-number" style={{fontSize:38}}>{p}</div><p className="muted">{d}</p><Link href="/pricing" className="btn secondary">VIEW PLAN</Link></div>)}</div></div></section>
<section className="section"><div className="container"><h2 className="section-title">FAQ</h2><div className="grid two"><div className="glass card"><h3>Is this another OP.GG?</h3><p className="muted">No. The product is designed around one actionable improvement mission, not stat browsing.</p></div><div className="glass card"><h3>Does it guarantee I climb?</h3><p className="muted">No. It measures your improvement signals and gives evidence-based coaching prompts; it does not predict MMR or guarantee rank gains.</p></div></div></div></section>
<section className="section"><div className="container glass card" style={{textAlign:'center',padding:'58px 24px'}}><div className="eyebrow">YOUR NEXT GAME SHOULD HAVE A PURPOSE</div><h2 className="section-title">STOP GUESSING.<br/>START IMPROVING.</h2><Link href="/signup" className="btn primary">ANALYSE MY GAMES</Link></div></section></main><footer className="footer"><div className="container">CLIMB//AI is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Verify required wording against current Riot developer policies before launch.</div></footer></>}
