'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {PageHead} from '@/components/UI';
import {useAccount,matchesFor} from '@/components/AccountContext';
import {useLearningPlan} from '@/components/LearningPlanContext';
import {missionEvidence} from '@/lib/missionLoop';
import type {ILPTask,Match} from '@/lib/types';

type SessionState={accountId:string;taskId:string;taskTitle:string;metric:string;startedAt:string;baselineMatchIds:string[];targetGames:number};
const KEY='op_climb_session_v1';

function loadSession():SessionState|null{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function saveSession(value:SessionState|null){try{if(value)localStorage.setItem(KEY,JSON.stringify(value));else localStorage.removeItem(KEY)}catch{}}
function verdict(task:ILPTask,games:Match[]){const evidence=games.map(game=>missionEvidence(task,game));const measured=evidence.filter(item=>item.available);const passed=measured.filter(item=>item.clearedBar).length;if(!games.length)return'Your focus is locked. Play your first tracked Ranked game and come back here.';if(!measured.length)return'We have the games, but not enough reliable evidence for this behaviour yet. OP CLIMB will not invent progress.';if(passed===measured.length&&measured.length>=2)return`You are repeating the behaviour: ${passed}/${measured.length} measured games cleared the mission bar. Keep proving it until the development plan marks it mastered.`;if(passed>0)return`There is improvement, but it is not stable yet: ${passed}/${measured.length} measured games cleared the bar. Keep the same focus for the next game.`;return'You are not clearing the behaviour bar yet. Do not add another concept — simplify the same rule and give it another deliberate game.'}

export default function ClimbSession(){
 const {active}=useAccount();const {tasks}=useLearningPlan();const matches=matchesFor(active.id);const activeTasks=tasks.filter(t=>t.status!=='MASTERED'&&t.status!=='PAUSED').slice(0,5);const lead=activeTasks[0];const [session,setSession]=useState<SessionState|null>(null);
 useEffect(()=>{const stored=loadSession();if(stored?.accountId===active.id)setSession(stored);else setSession(null)},[active.id]);
 const sessionTask=useMemo(()=>session?tasks.find(t=>t.id===session.taskId):undefined,[session,tasks]);
 const sessionGames=useMemo(()=>{if(!session)return[];const baseline=new Set(session.baselineMatchIds);return matches.filter(m=>!baseline.has(m.id)&&Date.parse(m.createdAt)>=Date.parse(session.startedAt)).slice().reverse().slice(0,session.targetGames)},[matches,session]);
 const task=sessionTask||lead;const complete=!!session&&sessionGames.length>=session.targetGames;
 const start=()=>{if(!lead)return;const next:SessionState={accountId:active.id,taskId:lead.id,taskTitle:lead.title,metric:lead.metric,startedAt:new Date().toISOString(),baselineMatchIds:matches.map(m=>m.id),targetGames:3};saveSession(next);setSession(next)};
 const finish=()=>{saveSession(null);setSession(null)};
 return <AppShell><PageHead title="Climb Session" subtitle={`${active.gameName}${active.tagline} · ${active.rank} · ${active.role}`}/><div className="v7-stack">
  {!session?<section className="hq-command"><div className="hq-top"><span className="v7-badge engine">COACHING BLOCK</span><span className="v7-badge">3 RANKED GAMES</span></div><h2>{lead?.title||'Play one tracked game first'}</h2><p>{lead?.why||'OP CLIMB needs reliable game evidence before it can set a deliberate session focus.'}</p>{lead&&<><div className="hq-rules"><div><span className="label">TODAY'S RULE</span><b>{lead.gameRule}</b></div><div><span className="label">MISSION BAR</span><b>{lead.target}</b></div></div><div className="glass card" style={{marginTop:16}}><div className="eyebrow">HOW THIS WORKS</div><p className="muted">Your #1 development behaviour is locked for the full session. OP CLIMB watches the next three tracked games, checks the same behaviour after each game, and keeps the lesson stable instead of throwing new advice at you.</p></div><div className="hero-actions"><button className="btn primary" onClick={start}>START 3-GAME SESSION →</button><Link className="btn secondary" href="/coach">ASK COACH FIRST</Link></div></>}</section>:
  <><section className="hq-command"><div className="hq-top"><span className="v7-badge engine">SESSION LIVE</span><span className="v7-badge">{sessionGames.length}/{session.targetGames} GAMES REVIEWED</span></div><h2>{task?.title||session.taskTitle}</h2><p>{task?.why}</p><div className="hq-rules"><div><span className="label">LOCKED GAME RULE</span><b>{task?.gameRule}</b></div><div><span className="label">SESSION TARGET</span><b>{task?.target}</b></div></div><div className="hero-actions">{!complete&&<Link className="btn primary" href="/live">PLAY GAME {sessionGames.length+1} WITH THIS →</Link>}<Link className="btn secondary" href="/coach">ASK COACH</Link></div></section>
  <section className="v7-section"><div className="v7-section-head"><div><div className="eyebrow">SESSION REVIEW</div><h2>One lesson. Three chances to prove it.</h2></div></div><div className="grid three">{[0,1,2].map(index=>{const game=sessionGames[index];const evidence=task&&game?missionEvidence(task,game):null;return <div key={index} className="glass card" style={{display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between'}}><span className="label">GAME {index+1}</span>{game?<strong className={game.result==='WIN'?'success':'danger'}>{game.result}</strong>:<span className="muted">WAITING</span>}</div>{game?<><h3 style={{margin:0}}>{game.champion} · {game.kills}/{game.deaths}/{game.assists}</h3><b>{evidence?.available?(evidence.clearedBar?'MISSION BAR CLEARED':'KEEP WORKING'):'EVIDENCE BUILDING'}</b><p className="muted" style={{margin:0}}>{evidence?.reason}</p><Link className="text-link" href={`/analyse/${encodeURIComponent(game.id)}`}>OPEN FULL REVIEW →</Link></>:<p className="muted">Your next tracked game will appear here automatically.</p>}</div>})}</div></section>
  <section className="glass card" style={{padding:'clamp(22px,4vw,38px)'}}><div className="eyebrow">COACH VERDICT</div><h2 style={{margin:'8px 0 12px'}}>{complete?'SESSION COMPLETE':'SESSION IN PROGRESS'}</h2><p style={{fontSize:16,lineHeight:1.65,maxWidth:780}}>{task?verdict(task,sessionGames):'Your original focus is no longer active. Finish the session and let the development plan choose the next evidence-backed limiter.'}</p>{complete&&<div className="hero-actions"><button className="btn primary" onClick={finish}>BANK SESSION & RETURN HOME →</button><Link className="btn secondary" href="/ilp">SEE DEVELOPMENT PLAN</Link></div>}</section></>}
 </div></AppShell>
}
