import {Wordmark} from '@/components/UI';
import {HUNT_STAGES} from '@/lib/brand';
import Link from 'next/link';
import {TrackView} from '@/components/TrackView';

export default function Landing(){return <>
<TrackView event="landing_view"/>
<header className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center',paddingTop:24}}><Wordmark/><div style={{display:'flex',gap:10}}><Link className="btn secondary" href="/login">LOG IN</Link><Link className="btn primary" href="/signup">START FREE</Link></div></header>
<main>
<section className="hero container"><div className="eyebrow">NOT ANOTHER LEAGUE STATS SITE</div><h1>ONE GAME.<br/>ONE LEAK.<br/><span style={{color:'var(--accent-2)'}}>ONE CUE.</span></h1><p>OVERPOWERED turns your match into one thing to carry into the next game — then checks whether you actually fixed it.</p><div className="hero-actions"><Link className="btn primary" href="/signup">FIND MY BIGGEST LEAK</Link><a className="btn secondary" href="#loop">SEE THE HUNT</a></div><p className="muted" style={{fontSize:13}}>No tier-list rabbit hole. No wall of stats. No ten-point coaching essay.</p>
<div className="climb-card-main" style={{marginTop:48}}><div className="climb-card-number">YOUR NEXT-GAME HUNT CARD</div><div className="climb-card-category">RESOURCE DISCIPLINE</div><h2>WIN THE WAVE<br/>BEFORE THE FIGHT.</h2><p className="climb-card-intro">Your lane is not the main problem. Your farm drops after 15 minutes when you follow your team mid without checking available gold.</p><div className="cue-stack"><div className="cue-row large"><span>TRIGGER</span><b>Every recall after 15:00</b></div><div className="cue-row large"><span>ACTION</span><b>Check both side waves before walking mid</b></div><div className="cue-row large"><span>PASS</span><b>6.5+ CS/min across 3 relevant games</b></div></div><div className="do-not"><span>DO NOT</span><strong>Autopilot mid just because your team is there.</strong></div></div>
</section>
<section className="section" id="loop"><div className="container"><div className="eyebrow">THE HUNT</div><h2 className="section-title">It behaves more like a training plan than a profile page.</h2><div className="grid five">{HUNT_STAGES.map(({step:n,name:t,detail:d})=><div className="glass card" key={n}><div className="eyebrow">{n}</div><h3>{t}</h3><p className="muted">{d}</p></div>)}</div></div></section>
<section className="section"><div className="container"><h2 className="section-title">Your stats are evidence.<br/>They are not the product.</h2><div className="grid two"><div className="glass card"><div className="eyebrow">MOST LEAGUE TOOLS</div><h3>Here are 40 numbers about your game.</h3><p className="muted">You still have to decide which matter, whether they are recurring, and what to remember next game.</p></div><div className="glass card mission-card"><div className="eyebrow">OVERPOWERED</div><h3>Here is the one behaviour we want repeated three times.</h3><p className="muted">Trigger → action → measurable pass condition. The focus stays active until the evidence changes.</p></div></div></div></section>
<section className="section"><div className="container glass card" style={{textAlign:'center',padding:'58px 24px'}}><div className="eyebrow">YOUR NEXT GAME SHOULD HAVE A PURPOSE</div><h2 className="section-title">PLAY LESS ON AUTOPILOT.</h2><Link href="/signup" className="btn primary">BUILD MY FIRST HUNT CARD</Link></div></section>
</main><footer className="footer"><div className="container">OVERPOWERED is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties.<div className="footer-links"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></footer>
</>}
