import {mitigateAll,noPenetration,type DamageBreakdown,type DamageComponent,type DamageType,type Penetration,type TargetResistances} from './damage';
import {applyDamageRules,attackInterval,hasteMultiplier,resolveOnHit,type AbilityModel,type AbilitySlot,type AutoAttackModel,type ComboStep} from './combos';
import {autoProcTriggers,onHitTriggers,type DamageRule,type TargetDebuffEffect} from './effects';
import {abilityCooldownSeconds,abilityDamageMultiplier,applyAbilityStackAfterCast,consumeMark,createCombatRuntime,timedAutoSnapshot,type CombatRuntimeState,type InitialTargetMark} from './state';
import {consumeRechargeableAttack,rechargeableAttackEffects,rechargeableAttackSpeedMultiplier,reduceRechargeableAttackCooldownOnAbilityHit} from './attackInteractions';
import {resolveRangeAccess} from './rangeAccess';
import type {AdvancedDuelAbilityOverlay,AdvancedDuelOpeningShield,DuelShieldScope,DuelSustainEffect} from './duelAdvanced';

export type BotLaneKey='YOU_ADC'|'YOU_SUPPORT'|'THEM_ADC'|'THEM_SUPPORT';
export type BotLaneTeam='YOU'|'THEM';
export type BotLaneRole='ADC'|'SUPPORT';
export type BotLaneVerdict='YOU_WIN'|'THEM_WIN'|'YOU_AHEAD'|'THEM_AHEAD'|'EVEN'|'DOUBLE_KO';

export interface AllyUtilityOverlay{shield?:{label:string;amount:number;durationSeconds:number|null;scope:DuelShieldScope};heal?:{label:string;amount:number}}
export interface BotLaneParticipantInput{
  key:BotLaneKey;team:BotLaneTeam;role:BotLaneRole;champion:string;sequence:ComboStep[];
  abilities:Partial<Record<AbilitySlot,AbilityModel>>;autoAttack:AutoAttackModel;mana:number;maxHealth:number;
  currentHealth?:number;shield?:number;openingShields?:AdvancedDuelOpeningShield[];resistances:TargetResistances;
  /** Static distance to specific enemy actors. Missing entries remain UNKNOWN. */
  targetDistances?:Partial<Record<BotLaneKey,number>>;
  penetration?:Penetration;abilityHaste?:number;damageRules?:DamageRule[];initialTargetMarks?:InitialTargetMark[];
  outgoingDamageMultiplier?:number;outgoingDamageMultiplierDurationSeconds?:number;
  abilityOverlays?:Partial<Record<AbilitySlot,AdvancedDuelAbilityOverlay>>;sustainEffects?:DuelSustainEffect[];
  focusTarget:BotLaneKey;protectTarget?:BotLaneKey;allyUtility?:Partial<Record<AbilitySlot,AllyUtilityOverlay>>;
}
export interface BotLaneSnapshot{key:BotLaneKey;champion:string;team:BotLaneTeam;role:BotLaneRole;health:number;maxHealth:number;shield:number;mana:number;alive:boolean;damageDealt:number;damageTaken:number;healingDone:number;shieldingDone:number;controlledUntil:number}
export interface BotLaneActionEvent{actor:BotLaneKey;champion:string;step:ComboStep;target:BotLaneKey|null;targetChampion:string|null;status:'CAST'|'NO_RESOURCE'|'NOT_LEARNED'|'NO_TARGET'|'OUT_OF_RANGE';rawDamage:number;mitigatedDamage:number;damageApplied:number;healApplied:number;shieldGranted:number;controlSeconds:number;note?:string;incomplete:boolean}
export interface BotLaneFrame{atSeconds:number;actions:BotLaneActionEvent[];participants:Record<BotLaneKey,BotLaneSnapshot>}
export interface BotLaneKill{atSeconds:number;victim:BotLaneKey;champion:string;team:BotLaneTeam;by:BotLaneKey[]}
export interface BotLaneResult{verdict:BotLaneVerdict;winner:BotLaneTeam|null;durationSeconds:number;timeline:BotLaneFrame[];kills:BotLaneKill[];participants:Record<BotLaneKey,BotLaneSnapshot>;teamDamage:{YOU:number;THEM:number};damageContribution:Record<BotLaneKey,number>;firstKill:BotLaneKill|null;incomplete:boolean;assumptions:string[];modelNote:string}
export interface BotLaneFocusComparison{recommendedTarget:BotLaneKey;recommendedRole:'ADC'|'SUPPORT';reason:string;adcFocus:BotLaneResult;supportFocus:BotLaneResult}

interface ActiveDebuff{effect:TargetDebuffEffect;expiresAt:number}
interface TimedShield{label:string;amount:number;expiresAt:number;scope:DuelShieldScope}
interface ActorRuntime{input:BotLaneParticipantInput;health:number;persistentShield:number;timedShields:TimedShield[];mana:number;autoCount:number;attackStacks:number;combat:CombatRuntimeState;incomingDebuffs:ActiveDebuff[];abilityReadyAt:Map<AbilitySlot,number>;autoReadyAt:number;nextFreeAt:number;controlledUntil:number;actionIndex:number;damageDealt:number;damageTaken:number;healingDone:number;shieldingDone:number;incomplete:boolean;consumedControlKeys:Set<string>}
interface PreparedAction{actor:ActorRuntime;target:ActorRuntime|null;protect:ActorRuntime|null;event:BotLaneActionEvent;breakdown?:DamageBreakdown;targetDebuff?:TargetDebuffEffect;targetControl?:NonNullable<AdvancedDuelAbilityOverlay['targetControl']>;overlay?:AdvancedDuelAbilityOverlay;allyUtility?:AllyUtilityOverlay}

const ORDER:BotLaneKey[]=['YOU_ADC','YOU_SUPPORT','THEM_ADC','THEM_SUPPORT'];const EPS=1e-9;const MAX_FRAMES=512;
export const BOT_LANE_MODEL_NOTE='Four champions share one deterministic event clock. Both bot laners on each team can damage, shield, heal and crowd-control while focus targets automatically swap after a death. Rechargeable attack passives use that same clock, qualifying ability hits can reduce their recharge, and ready-state passives can alter the attack interval that consumes them. Explicit per-target static distances can block known-range actions without inventing movement. Projectile travel, body-blocking, skillshot miss chance and minions are not inferred yet.';

export function simulateBotLane(inputs:Record<BotLaneKey,BotLaneParticipantInput>,maxDurationSeconds=10):BotLaneResult{
  const actors=Object.fromEntries(ORDER.map(k=>[k,createActor(inputs[k])])) as Record<BotLaneKey,ActorRuntime>,timeline:BotLaneFrame[]=[],kills:BotLaneKill[]=[];
  const assumptions=[BOT_LANE_MODEL_NOTE,'When multiple eligible shields overlap, the earliest-expiring timed shield is consumed first, then persistent shield.','If a configured focus target dies, that actor automatically retargets the surviving enemy. Range for a newly retargeted enemy is enforced only when that actor has an explicit distance entry.'];let clock=0;
  for(let frame=0;frame<MAX_FRAMES;frame++){
    if(teamDead(actors,'YOU')||teamDead(actors,'THEM'))break;
    const schedule=ORDER.map(key=>({key,at:nextActionAt(actors[key])})),next=Math.min(...schedule.map(x=>x.at));
    if(!Number.isFinite(next)||next>maxDurationSeconds+EPS){clock=Math.min(maxDurationSeconds,Number.isFinite(next)?next:maxDurationSeconds);break}
    clock=Math.max(clock,next);for(const key of ORDER)expireShields(actors[key],clock);
    const acting=schedule.filter(x=>Math.abs(x.at-clock)<=EPS).map(x=>actors[x.key]),beforeAlive=new Map(ORDER.map(k=>[k,actors[k].health>0]));
    const prepped=acting.map(actor=>preflight(actor,actors,clock)),actions=prepped.map(pre=>prepareDamage(pre,clock));
    for(const pre of actions){if(pre.event.status!=='CAST'||!pre.protect||!pre.allyUtility)continue;const utility=pre.allyUtility;if(utility.shield){const granted=grantTimedShield(pre.protect,utility.shield,clock);pre.actor.shieldingDone+=granted;pre.event.shieldGranted=round(granted)}if(utility.heal){const before=pre.protect.health;pre.protect.health=Math.min(pre.protect.input.maxHealth,pre.protect.health+positive(utility.heal.amount));const healed=Math.max(0,pre.protect.health-before);pre.actor.healingDone+=healed;pre.event.healApplied=round(healed)}}
    for(const pre of actions){if(pre.event.status!=='CAST'||!pre.target||!pre.breakdown)continue;const applied=applyIncomingBreakdown(pre.target,pre.breakdown,clock);pre.event.damageApplied=round(applied.healthDamage+applied.shieldDamage);pre.actor.damageDealt+=pre.event.damageApplied;pre.target.damageTaken+=pre.event.damageApplied}
    for(const pre of actions){if(pre.event.status!=='CAST')continue;let heal=0;for(const sustain of pre.actor.input.sustainEffects??[]){if(clock>=Math.max(0,sustain.durationSeconds)-EPS)continue;heal+=pre.event.damageApplied*Math.max(0,sustain.healFromDamageRatio)}if(heal>0){const before=pre.actor.health;pre.actor.health=Math.min(pre.actor.input.maxHealth,Math.max(0,pre.actor.health)+heal);const applied=Math.max(0,pre.actor.health-before);pre.actor.healingDone+=applied;pre.event.healApplied=round(pre.event.healApplied+applied)}}
    for(const pre of actions){if(pre.event.status!=='CAST'||!pre.target)continue;if(pre.targetDebuff)upsertDebuff(pre.target.incomingDebuffs,pre.targetDebuff,clock+pre.targetDebuff.durationSeconds);const control=pre.targetControl;if(control&&pre.target.health>0&&canApplyControl(pre.actor,control)){const lock=Math.max(0,finite(control.actionLockSeconds));if(lock>0)pre.target.controlledUntil=Math.max(pre.target.controlledUntil,clock+lock);if(control.consumeKey)pre.actor.consumedControlKeys.add(control.consumeKey);pre.event.controlSeconds=round(Math.max(0,finite(control.durationSeconds)))}}
    for(const victim of ORDER){if(!beforeAlive.get(victim)||actors[victim].health>0)continue;const attackers=actions.filter(a=>a.target?.input.key===victim&&a.event.damageApplied>0).map(a=>a.actor.input.key);kills.push({atSeconds:round(clock),victim,champion:actors[victim].input.champion,team:actors[victim].input.team,by:[...new Set(attackers)]})}
    timeline.push({atSeconds:round(clock),actions:actions.map(a=>a.event),participants:snapshots(actors,clock)});
  }
  const final=snapshots(actors,clock),winner=winnerFrom(final),verdict=verdictFrom(final,winner,kills),teamDamage={YOU:round(final.YOU_ADC.damageDealt+final.YOU_SUPPORT.damageDealt),THEM:round(final.THEM_ADC.damageDealt+final.THEM_SUPPORT.damageDealt)},damageContribution=Object.fromEntries(ORDER.map(key=>[key,final[key].damageDealt])) as Record<BotLaneKey,number>;
  return {verdict,winner,durationSeconds:round(clock),timeline,kills,participants:final,teamDamage,damageContribution,firstKill:kills[0]??null,incomplete:ORDER.some(key=>actors[key].incomplete),assumptions,modelNote:BOT_LANE_MODEL_NOTE};
}

export function compareYourFocusTargets(inputs:Record<BotLaneKey,BotLaneParticipantInput>,maxDurationSeconds=10):BotLaneFocusComparison{
  const adcInputs=cloneInputs(inputs);adcInputs.YOU_ADC.focusTarget='THEM_ADC';adcInputs.YOU_SUPPORT.focusTarget='THEM_ADC';const supportInputs=cloneInputs(inputs);supportInputs.YOU_ADC.focusTarget='THEM_SUPPORT';supportInputs.YOU_SUPPORT.focusTarget='THEM_SUPPORT';
  const adcFocus=simulateBotLane(adcInputs,maxDurationSeconds),supportFocus=simulateBotLane(supportInputs,maxDurationSeconds),adcScore=focusScore(adcFocus,'YOU'),supportScore=focusScore(supportFocus,'YOU'),recommendAdc=adcScore>=supportScore,chosen=recommendAdc?adcFocus:supportFocus,target=recommendAdc?'THEM_ADC':'THEM_SUPPORT',targetName=chosen.participants[target].champion,delta=Math.abs(adcScore-supportScore);
  return {recommendedTarget:target,recommendedRole:recommendAdc?'ADC':'SUPPORT',reason:delta<5?`Both focus plans are close. ${targetName} is the slight deterministic edge, but access/skillshot reliability can override it.`:`Focusing ${targetName} produces the stronger team-health/kill outcome in this exact setup (${round(Math.max(adcScore,supportScore))} vs ${round(Math.min(adcScore,supportScore))} focus score).`,adcFocus,supportFocus};
}

function preflight(actor:ActorRuntime,actors:Record<BotLaneKey,ActorRuntime>,clock:number):PreparedAction{
  const step=actor.input.sequence[actor.actionIndex],target=chooseEnemyTarget(actor,actors),protect=chooseProtectTarget(actor,actors),event:BotLaneActionEvent={actor:actor.input.key,champion:actor.input.champion,step,target:target?.input.key??null,targetChampion:target?.input.champion??null,status:'CAST',rawDamage:0,mitigatedDamage:0,damageApplied:0,healApplied:0,shieldGranted:0,controlSeconds:0,incomplete:false};
  if(!target){actor.actionIndex++;return {actor,target:null,protect,event:{...event,status:'NO_TARGET',note:'No living enemy target.'}}}
  const distance=actor.input.targetDistances?.[target.input.key];
  if(step==='AA'){
    const access=resolveRangeAccess(distance,actor.input.autoAttack.rangeUnits,'Basic attack');if(access.status==='OUT_OF_RANGE'){actor.actionIndex++;return {actor,target,protect,event:{...event,status:'OUT_OF_RANGE',note:access.note}}}
    const timed=timedAutoSnapshot(actor.input.autoAttack.timedStates,clock),cost=timed.resourceCostOverride??positive(actor.input.autoAttack.resourceCost??0);if(cost>actor.mana+EPS){actor.actionIndex++;return {actor,target,protect,event:{...event,status:'NO_RESOURCE',note:`Basic attack costs ${round(cost)} resource; only ${round(actor.mana)} remains.`}}}actor.mana-=cost;return {actor,target,protect,event};
  }
  const ability=actor.input.abilities[step];if(!ability){actor.actionIndex++;return {actor,target,protect,event:{...event,status:'NOT_LEARNED',note:`${step} is not learned or available.`}}}event.target=target.input.key;event.targetChampion=target.input.champion;
  const access=resolveRangeAccess(distance,ability.rangeUnits,ability.name);if(access.status==='OUT_OF_RANGE'){actor.actionIndex++;return {actor,target,protect,event:{...event,status:'OUT_OF_RANGE',note:access.note}}}
  const cost=positive(ability.cost);if(cost>actor.mana+EPS){actor.actionIndex++;return {actor,target,protect,event:{...event,status:'NO_RESOURCE',note:`${ability.name} costs ${round(cost)} resource; only ${round(actor.mana)} remains.`}}}actor.mana-=cost;
  const overlay=actor.input.abilityOverlays?.[step],selfShield=overlay?.selfShield;if(selfShield&&(selfShield.timing??'CAST_START')==='CAST_START'){const granted=grantTimedShield(actor,selfShield,clock);actor.shieldingDone+=granted;event.shieldGranted=round(granted)}const selfHeal=overlay?.selfHeal;if(selfHeal&&(selfHeal.timing??'CAST_START')==='CAST_START'){const before=actor.health;actor.health=Math.min(actor.input.maxHealth,actor.health+positive(selfHeal.amount));const healed=Math.max(0,actor.health-before);actor.healingDone+=healed;event.healApplied=round(healed)}return {actor,target,protect,event,targetDebuff:ability.targetDebuff,targetControl:overlay?.targetControl,overlay,allyUtility:actor.input.allyUtility?.[step]};
}

function prepareDamage(pre:PreparedAction,clock:number):PreparedAction{
  const {actor,target,event}=pre;if(event.status!=='CAST'||!target)return pre;
  if(event.step==='AA'){
    const model=actor.input.autoAttack,timed=timedAutoSnapshot(model.timedStates,clock),nextAuto=actor.autoCount+1,replacementEffects=rechargeableAttackEffects(model,actor.combat,clock),readyAttackSpeedMultiplier=rechargeableAttackSpeedMultiplier(model,actor.combat,clock),components:DamageComponent[]=replacementEffects?.length?replacementEffects.map(effect=>resolveOnHit(effect,target.health,target.input.maxHealth)):[{label:'Auto attack',type:'PHYSICAL',raw:positive(model.damage)*timed.basicAttackDamageMultiplier}];
    for(const effect of [...(model.onHits??[]),...timed.onHits])if(onHitTriggers(effect,nextAuto))components.push(resolveOnHit(effect,target.health,target.input.maxHealth));for(const consumer of model.eventState?.consumesMarks??[])if(consumeMark(actor.combat,consumer,clock))components.push(resolveOnHit(consumer.damage,target.health,target.input.maxHealth));for(const proc of model.autoProcs??[])if(autoProcTriggers(proc,nextAuto))components.push(resolveOnHit(proc.damage,target.health,target.input.maxHealth));const stack=model.attackStack;if(stack?.onHitAtMax&&actor.attackStacks>=stack.maxStacks)components.push(resolveOnHit(stack.onHitAtMax,target.health,target.input.maxHealth));const adjusted=applyDamageRules(components,actor.input.damageRules??[],target.health,target.input.maxHealth,actor.autoCount,outgoingMultiplier(actor,clock)),result=mitigateAll(adjusted,resistancesAt(target,clock),actor.input.penetration??noPenetration());pre.breakdown=result;event.rawDamage=result.rawTotal;event.mitigatedDamage=result.mitigatedTotal;event.incomplete=!result.complete;actor.incomplete||=!result.complete;const passiveProc=replacementEffects?.length?consumeRechargeableAttack(model,actor.combat,clock):null;if(passiveProc){event.note=`${passiveProc.label} consumed; passive ready at ${passiveProc.readyAt}s before later refunds.`;if(readyAttackSpeedMultiplier!==1)event.note+=` ${round((readyAttackSpeedMultiplier-1)*100)}% ready-state attack speed applied to this attack interval.`}actor.autoCount=nextAuto;if(stack)actor.attackStacks=Math.min(stack.maxStacks,actor.attackStacks+1);actor.autoReadyAt=clock+attackInterval(currentAttackSpeed(model,actor.attackStacks,timed,readyAttackSpeedMultiplier));actor.nextFreeAt=actor.autoReadyAt;actor.actionIndex++;return pre;
  }
  const ability=actor.input.abilities[event.step];if(!ability)return pre;const components:DamageComponent[]=[...ability.damage,...(ability.dynamicDamage??[]).map(effect=>resolveOnHit(effect,target.health,target.input.maxHealth))];for(const consumer of ability.eventState?.consumesMarks??[])if(consumeMark(actor.combat,consumer,clock))components.push(resolveOnHit(consumer.damage,target.health,target.input.maxHealth));const stackRule=ability.eventState?.stackRule,multiplier=abilityDamageMultiplier(actor.combat,stackRule,clock),stateAdjusted=multiplier===1?components:components.map(c=>c.raw===null?c:{...c,raw:round(c.raw*multiplier)}),adjusted=applyDamageRules(stateAdjusted,actor.input.damageRules??[],target.health,target.input.maxHealth,actor.autoCount,outgoingMultiplier(actor,clock)),result=mitigateAll(adjusted,resistancesAt(target,clock),actor.input.penetration??noPenetration());pre.breakdown=result;event.rawDamage=result.rawTotal;event.mitigatedDamage=result.mitigatedTotal;event.incomplete=!result.complete;actor.incomplete||=!result.complete;const passiveRefund=reduceRechargeableAttackCooldownOnAbilityHit(actor.input.autoAttack,actor.combat,ability,clock);if(passiveRefund)event.note=`${passiveRefund.label}: ability hit refunded ${passiveRefund.reduction}s; passive ready at ${passiveRefund.after}s.`;const cooldownBase=abilityCooldownSeconds(ability.cooldownSeconds,actor.combat,stackRule,clock);applyAbilityStackAfterCast(actor.combat,stackRule,clock);actor.abilityReadyAt.set(event.step,clock+cooldownBase*hasteMultiplier(actor.input.abilityHaste??0));const castTime=Math.max(0,positive(ability.castTimeSeconds));actor.nextFreeAt=clock+castTime;if(ability.eventState?.resetsBasicAttackTimer)actor.autoReadyAt=Math.min(actor.autoReadyAt,clock+castTime);actor.actionIndex++;return pre;
}

function createActor(input:BotLaneParticipantInput):ActorRuntime{const maxHealth=Math.max(1,positive(input.maxHealth)),current=Math.min(maxHealth,Math.max(0,finiteOr(input.currentHealth,maxHealth))),stackRules=Object.values(input.abilities).map(a=>a?.eventState?.stackRule).filter((x):x is NonNullable<typeof x>=>Boolean(x)),timedShields=(input.openingShields??[]).filter(s=>positive(s.amount)>0).map(s=>({label:s.label,amount:positive(s.amount),expiresAt:s.durationSeconds===null?Infinity:Math.max(0,s.durationSeconds),scope:s.scope}));return {input:{...input,maxHealth},health:current,persistentShield:positive(input.shield??0),timedShields,mana:positive(input.mana),autoCount:0,attackStacks:0,combat:createCombatRuntime(stackRules,input.initialTargetMarks??[]),incomingDebuffs:[],abilityReadyAt:new Map(),autoReadyAt:0,nextFreeAt:0,controlledUntil:0,actionIndex:0,damageDealt:0,damageTaken:0,healingDone:0,shieldingDone:0,incomplete:false,consumedControlKeys:new Set()}}
function nextActionAt(actor:ActorRuntime){if(actor.health<=0||actor.actionIndex>=actor.input.sequence.length)return Infinity;const step=actor.input.sequence[actor.actionIndex];let ready=Math.max(actor.nextFreeAt,actor.controlledUntil);if(step==='AA')return Math.max(ready,actor.autoReadyAt);return Math.max(ready,actor.abilityReadyAt.get(step)??0)}
function chooseEnemyTarget(actor:ActorRuntime,actors:Record<BotLaneKey,ActorRuntime>){const preferred=actors[actor.input.focusTarget];if(preferred&&preferred.health>0&&preferred.input.team!==actor.input.team)return preferred;return ORDER.map(k=>actors[k]).find(a=>a.input.team!==actor.input.team&&a.health>0)??null}
function chooseProtectTarget(actor:ActorRuntime,actors:Record<BotLaneKey,ActorRuntime>){const key=actor.input.protectTarget;if(key&&actors[key]?.health>0&&actors[key].input.team===actor.input.team)return actors[key];return ORDER.map(k=>actors[k]).find(a=>a.input.team===actor.input.team&&a.input.role==='ADC'&&a.health>0)??actor}
function canApplyControl(actor:ActorRuntime,control:NonNullable<AdvancedDuelAbilityOverlay['targetControl']>){return !control.consumeKey||!actor.consumedControlKeys.has(control.consumeKey)}
function grantTimedShield(actor:ActorRuntime,shield:{label:string;amount:number;durationSeconds:number|null;scope:DuelShieldScope},clock:number){const amount=positive(shield.amount);if(amount<=0)return 0;actor.timedShields.push({label:shield.label,amount,expiresAt:shield.durationSeconds===null?Infinity:clock+Math.max(0,shield.durationSeconds),scope:shield.scope});return amount}
function expireShields(actor:ActorRuntime,clock:number){actor.timedShields=actor.timedShields.filter(s=>s.amount>EPS&&s.expiresAt>clock+EPS)}
function applyIncomingBreakdown(actor:ActorRuntime,breakdown:DamageBreakdown,clock:number){expireShields(actor,clock);let healthDamage=0,shieldDamage=0;for(const component of [...breakdown.components]){let remaining=Math.max(0,component.mitigated);actor.timedShields.sort((a,b)=>a.expiresAt-b.expiresAt);for(const shield of actor.timedShields){if(remaining<=EPS)break;if(!shieldEligible(shield.scope,component.type))continue;const used=Math.min(shield.amount,remaining);shield.amount-=used;remaining-=used;shieldDamage+=used}expireShields(actor,clock);if(remaining>EPS&&actor.persistentShield>0){const used=Math.min(actor.persistentShield,remaining);actor.persistentShield-=used;remaining-=used;shieldDamage+=used}const hp=Math.min(actor.health,remaining);actor.health=Math.max(0,actor.health-hp);healthDamage+=hp}return {healthDamage:round(healthDamage),shieldDamage:round(shieldDamage)}}
function shieldEligible(scope:DuelShieldScope,type:DamageType){return scope==='ALL'||(scope==='PHYSICAL'&&type==='PHYSICAL')||(scope==='MAGIC'&&type==='MAGIC')}
function resistancesAt(actor:ActorRuntime,clock:number){actor.incomingDebuffs=actor.incomingDebuffs.filter(d=>d.expiresAt>clock+EPS);const armorKeep=actor.incomingDebuffs.reduce((m,d)=>m*(1-clamp01(d.effect.percentArmorReduction??0)),1),mrKeep=actor.incomingDebuffs.reduce((m,d)=>m*(1-clamp01(d.effect.percentMagicResistReduction??0)),1);return {armor:round(actor.input.resistances.armor*armorKeep),magicResist:round(actor.input.resistances.magicResist*mrKeep)}}
function upsertDebuff(active:ActiveDebuff[],effect:TargetDebuffEffect,expiresAt:number){const found=active.find(d=>d.effect.label===effect.label);if(found){found.effect=effect;found.expiresAt=expiresAt}else active.push({effect,expiresAt})}
function currentAttackSpeed(model:AutoAttackModel,stacks:number,timed:ReturnType<typeof timedAutoSnapshot>,readyStateMultiplier=1){const extra=model.attackStack?model.attackStack.attackSpeedPerStack*stacks:0,cap=Number.isFinite(model.attackSpeedCap)&&Number(model.attackSpeedCap)>0?Number(model.attackSpeedCap):3;return Math.min(cap,Math.max(0,(model.attackSpeed+extra+timed.attackSpeedFlat)*timed.attackSpeedMultiplier*Math.max(0,readyStateMultiplier)))}
function outgoingMultiplier(actor:ActorRuntime,clock:number){const duration=Math.max(0,actor.input.outgoingDamageMultiplierDurationSeconds??0);if(duration<=0||clock>=duration-EPS)return 1;return Number.isFinite(actor.input.outgoingDamageMultiplier)?Math.max(0,actor.input.outgoingDamageMultiplier as number):1}
function teamDead(actors:Record<BotLaneKey,ActorRuntime>,team:BotLaneTeam){return ORDER.filter(k=>actors[k].input.team===team).every(k=>actors[k].health<=0)}
function snapshots(actors:Record<BotLaneKey,ActorRuntime>,clock:number){return Object.fromEntries(ORDER.map(k=>[k,snapshot(actors[k],clock)])) as Record<BotLaneKey,BotLaneSnapshot>}
function snapshot(actor:ActorRuntime,clock:number):BotLaneSnapshot{expireShields(actor,clock);return {key:actor.input.key,champion:actor.input.champion,team:actor.input.team,role:actor.input.role,health:round(actor.health),maxHealth:round(actor.input.maxHealth),shield:round(actor.persistentShield+actor.timedShields.reduce((n,s)=>n+s.amount,0)),mana:round(actor.mana),alive:actor.health>0,damageDealt:round(actor.damageDealt),damageTaken:round(actor.damageTaken),healingDone:round(actor.healingDone),shieldingDone:round(actor.shieldingDone),controlledUntil:round(Math.max(clock,actor.controlledUntil))}}
function winnerFrom(p:Record<BotLaneKey,BotLaneSnapshot>):BotLaneTeam|null{const youAlive=p.YOU_ADC.alive||p.YOU_SUPPORT.alive,themAlive=p.THEM_ADC.alive||p.THEM_SUPPORT.alive;if(youAlive&&!themAlive)return'YOU';if(themAlive&&!youAlive)return'THEM';return null}
function verdictFrom(p:Record<BotLaneKey,BotLaneSnapshot>,winner:BotLaneTeam|null,kills:BotLaneKill[]):BotLaneVerdict{if(winner==='YOU')return'YOU_WIN';if(winner==='THEM')return'THEM_WIN';if(!p.YOU_ADC.alive&&!p.YOU_SUPPORT.alive&&!p.THEM_ADC.alive&&!p.THEM_SUPPORT.alive)return'DOUBLE_KO';const you=teamHealthShare(p,'YOU'),them=teamHealthShare(p,'THEM');if(Math.abs(you-them)<.05)return'EVEN';return you>them?'YOU_AHEAD':'THEM_AHEAD'}
function teamHealthShare(p:Record<BotLaneKey,BotLaneSnapshot>,team:BotLaneTeam){const list=ORDER.map(k=>p[k]).filter(x=>x.team===team);return list.reduce((n,x)=>n+x.health+x.shield,0)/Math.max(1,list.reduce((n,x)=>n+x.maxHealth,0))}
function focusScore(r:BotLaneResult,team:BotLaneTeam){const enemy=team==='YOU'?'THEM':'YOU',ownDeaths=r.kills.filter(k=>k.team===team).length,enemyDeaths=r.kills.filter(k=>k.team===enemy).length,ownShare=teamHealthShare(r.participants,team),enemyShare=teamHealthShare(r.participants,enemy);return (enemyDeaths-ownDeaths)*100+(ownShare-enemyShare)*50}
function cloneInputs(inputs:Record<BotLaneKey,BotLaneParticipantInput>){return Object.fromEntries(ORDER.map(k=>[k,{...inputs[k],sequence:[...inputs[k].sequence],openingShields:[...(inputs[k].openingShields??[])],targetDistances:{...(inputs[k].targetDistances??{})},abilityOverlays:{...(inputs[k].abilityOverlays??{})},allyUtility:{...(inputs[k].allyUtility??{})}}])) as Record<BotLaneKey,BotLaneParticipantInput>}
const clamp01=(n:number)=>Math.min(1,Math.max(0,Number.isFinite(n)?n:0)),positive=(n:number)=>Number.isFinite(n)&&n>0?n:0,finite=(n:number|undefined)=>Number.isFinite(n)?n as number:0,finiteOr=(n:number|undefined,fallback:number)=>Number.isFinite(n)?n as number:fallback,round=(n:number)=>Math.round(n*100)/100;
