'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {getSupabaseBrowser} from '@/lib/supabaseBrowser';
export default function Login(){const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 async function google(){setBusy(true);setMsg('');const sb=getSupabaseBrowser();if(!sb){setMsg('Google sign-in is ready but Supabase keys are not connected yet. Use Demo Login for now.');setBusy(false);return}const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/dashboard`}});if(error){setMsg(error.message);setBusy(false)}}
 async function login(){const sb=getSupabaseBrowser();if(!sb){router.push('/dashboard');return}setBusy(true);const {error}=await sb.auth.signInWithPassword({email,password});setBusy(false);if(error)setMsg(error.message);else router.push('/dashboard')}
 return <main className="container section"><div className="logo">CLIMB<span>//AI</span></div><div className="glass card form" style={{margin:'55px auto'}}><div className="eyebrow">WELCOME BACK</div><h1>Log in</h1><label className="field"><span>Email</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field"><span>Password</span><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="login-actions"><button className="btn primary" onClick={login} disabled={busy}>LOG IN</button><button className="btn google-btn" onClick={google} disabled={busy}><span className="google-g">G</span> CONTINUE WITH GOOGLE</button></div>{msg&&<div className="auth-message">{msg}</div>}<div className="divider"/><p className="muted">Testing without Supabase? <Link href="/dashboard" className="text-link">ENTER DEMO MODE →</Link></p><p className="muted" style={{fontSize:12}}>Google OAuth requires Supabase Authentication + a Google provider configured with your Vercel URL. The button now uses the real OAuth flow when those keys exist instead of being a dead control.</p></div></main>}
