import Link from 'next/link';
import {Match,Mission} from '@/lib/types';
export function PageHead({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-head"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{action}</div>}
export function MetricCard({label,value,detail}:{label:string;value:string|number;detail?:string}){return <div className="glass card"><div className="label">{label}</div><div className="metric">{value}</div>{detail&&<div className="muted" style={{fontSize:13}}>{detail}</div>}</div>}
export function ProgressBar({value}:{value:number}){return <div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function MissionCard({mission}:{mission:Mission}){const p=Math.round((mission.gamesCompleted/mission.gamesRequired)*100);return <div className="glass card mission-card"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="eyebrow">YOUR CURRENT MISSION</div><h2 className="mission-title">{mission.title}</h2></div><span className="pill">{mission.status}</span></div><div className="grid two"><div><div className="label">TARGET</div><div className="big-number">{mission.target}</div><div className="muted">{mission.unit}</div></div><div><div className="label">GAMES</div><div className="big-number">{mission.gamesCompleted}/{mission.gamesRequired}</div><div className="muted">Repeat before changing focus</div></div></div><div style={{margin:'20px 0 10px'}}><ProgressBar value={p}/></div><ol className="muted">{mission.rules.map(x=><li key={x} style={{margin:'8px 0'}}>{x}</li>)}</ol><Link className="btn primary" href="/analyse">I&apos;M PLAYING NOW</Link></div>}
export function MatchCard({match}:{match:Match}){return <div className="glass card"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="eyebrow">{match.champion} · {match.role}</div><h3 style={{margin:'8px 0'}}>{match.result==='WIN'?<span className="success">VICTORY</span>:<span className="danger">DEFEAT</span>}</h3></div><span className="pill">{match.rank}</span></div><div className="grid four"><div><div className="label">KDA</div><strong>{match.kills}/{match.deaths}/{match.assists}</strong></div><div><div className="label">CS</div><strong>{match.metrics.cs}</strong></div><div><div className="label">CS/MIN</div><strong>{match.metrics.csPerMin.toFixed(1)}</strong></div><div><div className="label">DURATION</div><strong>{Math.floor(match.durationSeconds/60)}:{String(match.durationSeconds%60).padStart(2,'0')}</strong></div></div><Link href={`/analyse/${match.id}`} className="btn secondary" style={{marginTop:16}}>ANALYSE THIS GAME</Link></div>}
export function ClimbScore({score}:{score:number}){return <div className="glass card"><div className="label">CLIMB SCORE</div><div style={{display:'flex',gap:20,alignItems:'center',marginTop:14}}><div className="score"><strong>{score}</strong></div><div><strong className="success">+6</strong><div className="muted">over previous 10 games</div><p className="muted" style={{fontSize:13}}>Internal improvement score. It does not predict Riot MMR.</p></div></div></div>}
export function EmptyState({title,body,href,label}:{title:string;body:string;href:string;label:string}){return <div className="glass card" style={{textAlign:'center',padding:42}}><div className="eyebrow">START HERE</div><h2>{title}</h2><p className="muted">{body}</p><Link className="btn primary" href={href}>{label}</Link></div>}
