'use client';
import {useMemo,useState} from 'react';
import {useSubscription} from './SubscriptionContext';
import {canUseMetric,METRIC_TIER,PLAN_COPY,type CoachingMetricKey,type SubscriptionTier} from '@/lib/subscription';
import type {ProMatchAnalysis,ProMetric} from '@/lib/riot/proAnalysis';
import type {ProLearningProfile,ProHistoryFix} from '@/lib/riot/proHistory';

export type FightReview={
  atSeconds:number;category:'STRENGTH'|'WEAKNESS';outcome:'KILL'|'DEATH'|'ASSIST';opponent:string|null;opponentChampion:string|null;
  score:number;verdict:'YOU_STRONGER'|'EVEN'|'THEM_STRONGER';headline:string;summary:string;
  evidence:{youLevel:number;themLevel:number|null;levelDelta:number|null;youItemGold:number;themItemGold:number|null;itemGoldDelta:number|null;currentGold:number;healthPct:number|null;manaPct:number|null};
  why:string[];howToWin:string[];howYouLose:string[];betterDecision:string[];limitation:string;
};
type GradeBand='BROKEN'|'EXPOSED'|'STABLE'|'SHARP'|'OVERPOWERED';
type Severity='CRITICAL LEAK'|'MAJOR LEAK'|'ACTIVE LEAK'|'POLISH';
type FixStage='QUICK WIN'|'CONTROL'|'DISCIPLINE'|'ADVANCED'|'MASTERY';
type Fix={id:string;stage:FixStage;difficulty:number;severity:Severity;title:string;oneLine:string;evidence:FightReview[];rule:string;mastery:string;why:string};

const METRIC_ORDER:CoachingMetricKey[]=[
  'fight_selection','death_control','cs_curve','unspent_gold','red_state_fights','chain_deaths','thrown_advantage','underdog_conversion','fight_conversion','resource_conversion',
  'lead_protection','power_spike_conversion','reset_quality','objective_readiness','farm_fight_tradeoff','repeat_threat','opponent_adaptation','item_timing_diff','build_response','damage_efficiency','survival_value','carry_preservation','decision_fingerprint','historical_leak_rate','historical_recovery','champion_identity',
];

export function FightDecisionReview({fights,proAnalysis,historyProfile}:{fights:FightReview[];proAnalysis?:ProMatchAnalysis|null;historyProfile?:ProLearningProfile|null}){
  const {tier}=useSubscription();
  const [tab,setTab]=useState<'STRENGTH'|'WEAKNESS'>('WEAKNESS');
  const [openFight,setOpenFight]=useState<string|null>(null);
  const [openFix,setOpenFix]=useState<string|null>(null);
  const [openMetric,setOpenMetric]=useState<string|null>(null);
  const strengths=useMemo(()=>fights.filter(f=>f.category==='STRENGTH'),[fights]);
  const weaknesses=useMemo(()=>fights.filter(f=>f.category==='WEAKNESS'),[fights]);
  const grade=useMemo(()=>buildGrade(fights),[fights]);
  const currentFixes=useMemo(()=>buildFixes(fights),[fights]);
  const visible=tab==='STRENGTH'?strengths:weaknesses;
  const metrics=useMemo(()=>resolvedMetrics(fights,proAnalysis,historyProfile),[fights,proAnalysis,historyProfile]);
  const fixDepth=PLAN_COPY[tier].fixDepth;

  if(!fights.length&&!proAnalysis)return <div className="glass card"><div className="eyebrow">OP CLIMB GRADE</div><h3>Not enough decision evidence yet</h3><p className="muted">The match can still appear in history, but OP CLIMB needs player-involved event evidence before it assigns a decision grade or Fix Ladder.</p></div>;

  return <div style={{display:'grid',gap:16}}>
    <section className="glass card">
      <div style={topRow}><div><div className="eyebrow">OP CLIMB MATCH GRADE</div><h2 style={{margin:'5px 0 0'}}>Decision quality, not just KDA</h2></div><TierPill tier={tier}/></div>
      <div style={{display:'grid',gridTemplateColumns:'minmax(145px,.65fr) minmax(0,1.8fr)',gap:18,alignItems:'center',marginTop:16}}>
        <div><div style={{fontSize:56,fontWeight:950,lineHeight:.9,letterSpacing:'-.05em'}}>{grade.overall}</div><div style={{fontSize:17,fontWeight:900,letterSpacing:'.12em',marginTop:9}}>{grade.band}</div><small className="muted">OP DECISION SCORE / 100</small></div>
        <div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(125px,1fr))',gap:8}}>{grade.parts.map(p=><GradePart key={p.label} {...p}/>)}</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:12}}>{(['BROKEN','EXPOSED','STABLE','SHARP','OVERPOWERED'] as GradeBand[]).map(b=><span key={b} style={{...pill,opacity:b===grade.band?1:.35,fontWeight:b===grade.band?900:600}}>{b}</span>)}</div></div>
      </div>
    </section>

    <section className="glass card">
      <div className="eyebrow">ADVANCED OP METRICS</div><h2 style={{marginBottom:5}}>Choose the stat you want explained</h2><p className="muted" style={{marginTop:0}}>Measured, derived and building metrics are labelled differently. Click one to see what OP CLIMB used as evidence.</p>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(225px,1fr))',gap:9,marginTop:15}}>{metrics.map(m=><MetricCard key={m.key} metric={m} tier={tier} open={openMetric===m.key} onToggle={()=>setOpenMetric(openMetric===m.key?null:m.key)}/>)}</div>
    </section>

    <HistoryPanel tier={tier} profile={historyProfile}/>

    <section className="glass card">
      <div className="eyebrow">OP FIX LADDER</div><h2 style={{marginBottom:5}}>Start with the easy fix. Earn the harder ones.</h2><p className="muted" style={{marginTop:0}}>{tier} opens {fixDepth} stages per match. Each card stays closed until you choose to work on it.</p>
      {tier==='PRO'&&historyProfile?.fixLadder?.length?<div style={{marginTop:16}}><div className="eyebrow">MULTI-GAME PRIORITY</div><div style={{display:'grid',gap:9,marginTop:9}}>{historyProfile.fixLadder.map((fix,index)=><HistoryFixCard key={fix.key} fix={fix} index={index}/>)}</div></div>:null}
      <div style={{display:'grid',gap:9,marginTop:16}}>{currentFixes.length?currentFixes.map((fix,index)=>index<fixDepth?<FixCard key={fix.id} fix={fix} index={index} open={openFix===fix.id} onToggle={()=>setOpenFix(openFix===fix.id?null:fix.id)}/>:<LockedFixCard key={fix.id} fix={fix} index={index} required={index<4?'PLUS':'PRO'}/>):<div style={emptyStyle}><b>No serious current-match decision leak detected.</b><div className="muted" style={{fontSize:12,marginTop:4}}>Use Strengths below to see what OP CLIMB wants repeated.</div></div>}</div>
    </section>

    <section className="glass card">
      <div className="eyebrow">COACHING DECISION REVIEW</div><h2 style={{marginBottom:6}}>Strengths or weaknesses → choose a time → open the coaching</h2>
      <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,marginTop:16}}><TabButton active={tab==='STRENGTH'} type="strength" count={strengths.length} onClick={()=>{setTab('STRENGTH');setOpenFight(null)}}/><TabButton active={tab==='WEAKNESS'} type="weakness" count={weaknesses.length} onClick={()=>{setTab('WEAKNESS');setOpenFight(null)}}/></div>
      <div style={{display:'grid',gap:9,marginTop:16}}>{visible.length?visible.map((fight,index)=>{const key=`${fight.category}-${fight.atSeconds}-${index}`,open=openFight===key;return <div key={key} style={rowShell}><button type="button" onClick={()=>setOpenFight(open?null:key)} style={{...rowButton,gridTemplateColumns:'82px minmax(0,1fr) auto'}}><strong style={{fontSize:18}}>{formatClock(fight.atSeconds)}</strong><div><b>{fight.headline}</b><div className="muted" style={{fontSize:12,marginTop:2}}>{verdictLabel(fight.verdict)} · power {signed(fight.score)}</div></div><span>{open?'−':'+'}</span></button>{open&&<FightDetail fight={fight} tier={tier}/>}</div>}):<div style={emptyStyle}>No {tab.toLowerCase()} fight events were captured.</div>}</div>
    </section>
  </div>;
}

function MetricCard({metric,tier,open,onToggle}:{metric:DisplayMetric;tier:SubscriptionTier;open:boolean;onToggle:()=>void}){
  const required=METRIC_TIER[metric.key],unlocked=canUseMetric(tier,metric.key);
  return <div style={rowShell}><button type="button" onClick={unlocked?onToggle:undefined} style={{...rowButton,gridTemplateColumns:'minmax(0,1fr) auto',cursor:unlocked?'pointer':'default',opacity:unlocked?1:.7}}><div><div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'}}><span className="eyebrow">{metric.label}</span><DataPill status={metric.status}/></div><strong style={{display:'block',fontSize:21,marginTop:6}}>{unlocked?metric.value:'LOCKED 🔒'}</strong><div className="muted" style={{fontSize:10,marginTop:3}}>{required} · {metric.confidence} confidence</div></div><span>{unlocked?(open?'−':'+'):`${required} 🔒`}</span></button>{unlocked&&open?<div style={detailBody}><p style={{fontSize:13,lineHeight:1.55,marginTop:0}}>{metric.summary}</p>{metric.evidence.length?<div><div className="eyebrow">EVIDENCE</div><div style={{display:'grid',gap:7,marginTop:8}}>{metric.evidence.slice(0,8).map((e,i)=><div key={i} style={evidenceLine}>{e.atSeconds!==undefined?<b>{formatClock(e.atSeconds)}</b>:<b>{e.label}</b>}<span>{e.atSeconds!==undefined?`${e.label} — ${e.detail}`:e.detail}</span></div>)}</div></div>:<p className="muted" style={{fontSize:11,marginBottom:0}}>No timestamp evidence is available for this metric yet.</p>}<div className="muted" style={{fontSize:10,marginTop:12}}>Source: {metric.sources.join(' + ')}</div></div>:null}</div>;
}

type DisplayMetric={key:CoachingMetricKey;label:string;value:string;summary:string;status:string;confidence:string;sources:string[];evidence:{atSeconds?:number;label:string;detail:string}[]};
function resolvedMetrics(fights:FightReview[],analysis?:ProMatchAnalysis|null,history?:ProLearningProfile|null):DisplayMetric[]{
  const fallback=fallbackMetrics(fights);return METRIC_ORDER.map(key=>{
    const live=analysis?.metrics?.[key] as ProMetric|undefined;
    const roll=history?.metricRollups?.[key];
    if(['historical_leak_rate','historical_recovery','decision_fingerprint'].includes(key)&&roll){return{key,label:roll.label,value:roll.recentValue,summary:key==='decision_fingerprint'?history?.fingerprint?.explanation||'Persistent decision pattern across tracked games.':`Across ${roll.availableGames} available game${roll.availableGames===1?'':'s'}, average score ${roll.averageScore??'—'}/100. Trend: ${roll.trend}.`,status:roll.availableGames>=3?'MEASURED':'BUILDING',confidence:roll.availableGames>=5?'HIGH':'MEDIUM',sources:['MULTI_GAME_HISTORY'],evidence:[]}}
    if(live)return{key,label:live.label,value:live.value,summary:live.summary,status:live.status,confidence:live.confidence,sources:live.sources,evidence:live.evidence};
    return fallback.get(key)??{key,label:key.replaceAll('_',' ').toUpperCase(),value:'Building data',summary:'OP CLIMB has this metric in the PRO model, but this match did not expose enough evidence to calculate it reliably.',status:'BUILDING',confidence:'LOW',sources:['WAITING_FOR_EVIDENCE'],evidence:[]};
  });
}

function HistoryPanel({tier,profile}:{tier:SubscriptionTier;profile?:ProLearningProfile|null}){if(tier!=='PRO')return <section className="glass card" style={{opacity:.72}}><div className="eyebrow">PRO HISTORY ENGINE 🔒</div><h3>Learn the pattern across games, not just the last scoreline</h3><p className="muted">PRO tracks Decision Fingerprint, OP Leak Rate, Recovery trend, champion identity and a persistent Fix Ladder.</p></section>;if(!profile)return <section className="glass card"><div className="eyebrow">PRO HISTORY ENGINE</div><h3>Building your player model</h3><p className="muted">Complete tracked games and OP CLIMB will start comparing recurring behaviours automatically.</p></section>;return <section className="glass card"><div className="eyebrow">PRO HISTORY ENGINE</div><h2 style={{marginBottom:5}}>{profile.fingerprint.primary}</h2><p className="muted" style={{marginTop:0}}>{profile.fingerprint.explanation}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:8,marginTop:14}}><Mini label="GAMES LEARNED" value={String(profile.gamesAnalyzed)}/><Mini label="PATTERN RATE" value={`${profile.fingerprint.patternRate}%`}/><Mini label="TREND" value={profile.fingerprint.trend}/><Mini label="OP LEAK RATE" value={`${profile.opLeakRate.occurrencesPerGame}/game`}/></div>{profile.fingerprint.sequence.length?<details style={detailsStyle}><summary style={summaryStyle}>OPEN YOUR REPEATED LOSS SEQUENCE</summary><div style={{display:'grid',gap:7,marginTop:10}}>{profile.fingerprint.sequence.map((s,i)=><div key={i} style={evidenceLine}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></div>)}</div></details>:null}</section>}
function HistoryFixCard({fix,index}:{fix:ProHistoryFix;index:number}){return <details style={detailsStyle}><summary style={{...summaryStyle,display:'flex',justifyContent:'space-between',gap:10}}><span>{String(index+1).padStart(2,'0')} · {fix.stage} · {fix.title}</span><span>{fix.severity}</span></summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8,marginTop:10}}><MiniBlock label="WHY" text={fix.why}/><MiniBlock label="NEXT GAME RULE" text={fix.rule}/><MiniBlock label="MASTER IT WHEN" text={fix.mastery}/></div><p className="muted" style={{fontSize:11}}>Detected {fix.occurrences} times across {fix.gamesSeen} tracked games.</p></details>}

function FightDetail({fight,tier}:{fight:FightReview;tier:SubscriptionTier}){const e=fight.evidence;return <div style={detailBody}><div className="eyebrow">WHAT HAPPENED</div><p style={{fontSize:14,lineHeight:1.6}}>{fight.summary}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:8}}><Evidence label="LEVEL" value={e.themLevel===null?`L${e.youLevel}`:`L${e.youLevel} vs L${e.themLevel}`}/><Evidence label="ITEM EDGE" value={e.itemGoldDelta===null?'—':signedGold(e.itemGoldDelta)}/><Evidence label="HP" value={pctValue(e.healthPct)}/><Evidence label="RESOURCE" value={pctValue(e.manaPct)}/><Evidence label="POCKET GOLD" value={`${Math.round(e.currentGold)}g`}/></div><details style={detailsStyle}><summary style={summaryStyle}>{fight.category==='STRENGTH'?'WHY IT WORKED':'WHY IT FAILED'}</summary><CoachLines lines={fight.why}/></details>{tier!=='FREE'?<><details style={detailsStyle}><summary style={summaryStyle}>HOW YOU WIN IT</summary><CoachLines lines={fight.howToWin}/></details><details style={detailsStyle}><summary style={summaryStyle}>HOW YOU LOSE IT</summary><CoachLines lines={fight.howYouLose}/></details></>:<LockedDetail label="HOW YOU WIN / LOSE IT" tier="PLUS"/>}{tier==='PRO'?<details style={detailsStyle}><summary style={summaryStyle}>BETTER / REPEATABLE DECISION</summary><CoachLines lines={fight.betterDecision}/></details>:<LockedDetail label="BETTER / REPEATABLE DECISION" tier="PRO"/>}<small className="muted" style={{display:'block',marginTop:12}}>{fight.limitation}</small></div>}

function fallbackMetrics(fights:FightReview[]){const map=new Map<CoachingMetricKey,DisplayMetric>();const deaths=fights.filter(f=>f.outcome==='DEATH'),positives=fights.filter(f=>f.outcome!=='DEATH'),strong=fights.filter(f=>f.verdict==='YOU_STRONGER'),weak=fights.filter(f=>f.verdict==='THEM_STRONGER'),red=deaths.filter(f=>f.verdict==='THEM_STRONGER'),thrown=deaths.filter(f=>f.verdict==='YOU_STRONGER'),under=positives.filter(f=>f.verdict==='THEM_STRONGER'),ahead=positives.filter(f=>f.verdict==='YOU_STRONGER'),high=fights.filter(f=>f.evidence.currentGold>=900),chain=deaths.filter((f,i)=>i>0&&f.atSeconds-deaths[i-1].atSeconds<=90);const add=(key:CoachingMetricKey,label:string,value:string,summary:string)=>map.set(key,{key,label,value,summary,status:'DERIVED',confidence:'MEDIUM',sources:['FIGHT_EVENTS'],evidence:[]});add('fight_selection','FIGHT SELECTION',`${100-pct(red.length,Math.max(1,fights.length))}/100`,'Avoiding fights from already enemy-favoured states.');add('death_control','DEATH CONTROL',`${Math.max(0,100-deaths.length*10-thrown.length*10)}/100`,'Weights total deaths and thrown advantages.');add('unspent_gold','UNSPENT GOLD EXPOSURE',`${high.length} fights`,'Reviewed fights while carrying 900g+.');add('red_state_fights','RED-STATE FIGHT RATE',`${pct(red.length,Math.max(1,deaths.length))}%`,'Deaths taken while visibly weaker.');add('chain_deaths','CHAIN-DEATH RATE',`${pct(chain.length,Math.max(1,deaths.length))}%`,'Deaths within 90 seconds of a previous death.');add('thrown_advantage','THROWN ADVANTAGE RATE',`${pct(thrown.length,Math.max(1,strong.length))}%`,'Deaths from a visibly stronger state.');add('underdog_conversion','UNDERDOG CONVERSION',`${pct(under.length,Math.max(1,weak.length))}%`,'Positive conversions from a weaker visible state.');add('fight_conversion','POWER WINDOW CONVERSION',`${pct(ahead.length,Math.max(1,strong.length))}%`,'Positive outcomes from visibly stronger states.');add('resource_conversion','RESOURCE CONVERSION',`${Math.max(0,100-high.length*12)}/100`,'Whether gold was spent before reviewed fights.');add('lead_protection','LEAD PROTECTION',`${Math.max(0,100-thrown.length*25)}/100`,'How safely stronger states were protected.');return map}

function buildGrade(fights:FightReview[]){if(!fights.length)return{overall:50,band:'STABLE' as GradeBand,parts:[]};const deaths=fights.filter(f=>f.outcome==='DEATH'),positives=fights.filter(f=>f.outcome!=='DEATH'),red=deaths.filter(f=>f.verdict==='THEM_STRONGER').length,thrown=deaths.filter(f=>f.verdict==='YOU_STRONGER').length,even=deaths.filter(f=>f.verdict==='EVEN').length,high=fights.filter(f=>f.evidence.currentGold>=900).length,huge=deaths.filter(f=>f.evidence.currentGold>=1200).length,ahead=positives.filter(f=>f.verdict==='YOU_STRONGER').length,under=positives.filter(f=>f.verdict==='THEM_STRONGER').length;const selection=clamp(88-red*18-even*8-thrown*4+under*3),deathControl=clamp(92-deaths.length*9-thrown*14),resources=clamp(94-high*8-huge*14),powerUse=clamp(62+ahead*9+under*5-thrown*16),execution=clamp(64+positives.length*5+under*6-even*8-thrown*12),overall=Math.round(selection*.28+deathControl*.24+resources*.18+powerUse*.18+execution*.12);return{overall,band:gradeBand(overall),parts:[{label:'FIGHT SELECTION',score:selection},{label:'DEATH CONTROL',score:deathControl},{label:'RESOURCE USE',score:resources},{label:'POWER CONVERSION',score:powerUse},{label:'EXECUTION EVIDENCE',score:execution}]}}
function buildFixes(fights:FightReview[]):Fix[]{const deaths=fights.filter(f=>f.outcome==='DEATH'),rows:Fix[]=[];const high=deaths.filter(f=>f.evidence.currentGold>=900),red=deaths.filter(f=>f.verdict==='THEM_STRONGER'),chain=deaths.filter((f,i)=>i>0&&f.atSeconds-deaths[i-1].atSeconds<=90),thrown=deaths.filter(f=>f.verdict==='YOU_STRONGER'),low=deaths.filter(f=>(f.evidence.healthPct??1)<.55||(f.evidence.manaPct??1)<.3),even=deaths.filter(f=>f.verdict==='EVEN');const add=(id:string,stage:FixStage,difficulty:number,evidence:FightReview[],title:string,oneLine:string,rule:string,mastery:string,why:string)=>{if(evidence.length)rows.push({id,stage,difficulty,severity:severityFor(evidence.length),title,oneLine,evidence,rule,mastery,why})};add('bank','QUICK WIN',1,high,'SPEND BEFORE YOU FIGHT','Large unspent gold appeared at deaths.','If a safe reset buys meaningful power, bank before the next voluntary fight.','3 games with no reviewed death while carrying 900g+.','Unspent gold contributes zero combat stats.');add('red','CONTROL',2,red,'STOP ACCEPTING RED-STATE FIGHTS','You died after visible power had already moved against you.','Add numbers, setup or first damage before committing.','3 games with zero red-state reviewed deaths.','This is fight selection before mechanics.');add('chain','CONTROL',2,chain,'BREAK THE CHAIN DEATH','Another death followed inside 90 seconds.','After dying, stabilise before re-entering.','3 games with zero chain deaths.','The second death compounds the first loss.');add('throw','DISCIPLINE',3,thrown,'PROTECT YOUR ADVANTAGE','A stronger visible state still became your death.','Force the enemy to enter your threat instead of donating access.','3 games with no death from a clearly stronger state.','A lead only matters if it survives long enough to convert.');add('resource','DISCIPLINE',3,low,'STOP FIGHTING ON EMPTY','Low HP/resource reduced your margin.','Check HP/resource before committing.','3 games with no danger-state reviewed death.','Low resources turn small execution errors into deaths.');add('even','ADVANCED',4,even,'WIN THE SETUP FIRST','Raw visible power was close.','Earn numbers, first damage, terrain, CC or safer target access first.','Across 3 games, win more even-state fights than you lose.','When stats are close, setup decides the fight.');return rows.sort((a,b)=>a.difficulty-b.difficulty).slice(0,5)}

function TabButton({active,type,count,onClick}:{active:boolean;type:'strength'|'weakness';count:number;onClick:()=>void}){return <button type="button" onClick={onClick} style={tabStyle(active,type)}><span className="eyebrow">{type==='strength'?'STRENGTHS':'WEAKNESSES'}</span><strong style={{fontSize:25}}>{count}</strong><small>{type==='strength'?'positive conversions':'review points / deaths'}</small></button>}
function LockedFixCard({fix,index,required}:{fix:Fix;index:number;required:'PLUS'|'PRO'}){return <div style={{...rowShell,opacity:.65}}><div style={rowButton}><b>{String(index+1).padStart(2,'0')}</b><div><small>{fix.stage} · {required} 🔒</small><b style={{display:'block',marginTop:4}}>{fix.title}</b></div><span>🔒</span></div></div>}
function FixCard({fix,index,open,onToggle}:{fix:Fix;index:number;open:boolean;onToggle:()=>void}){return <div style={rowShell}><button type="button" onClick={onToggle} style={rowButton}><b>{String(index+1).padStart(2,'0')}</b><div><div><small>{fix.stage}</small> <SeverityPill severity={fix.severity}/></div><b style={{display:'block',marginTop:5}}>{fix.title}</b><div className="muted" style={{fontSize:12}}>{fix.oneLine} · {fix.evidence.length} evidence point{fix.evidence.length===1?'':'s'}</div></div><span>{open?'−':'+'}</span></button>{open?<div style={detailBody}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8}}><MiniBlock label="WHY" text={fix.why}/><MiniBlock label="NEXT GAME RULE" text={fix.rule}/><MiniBlock label="MASTER IT WHEN" text={fix.mastery}/></div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:12}}>{fix.evidence.slice(0,8).map((f,i)=><span key={i} style={pill}>{formatClock(f.atSeconds)} · {f.outcome}</span>)}</div></div>:null}</div>}
function LockedDetail({label,tier}:{label:string;tier:'PLUS'|'PRO'}){return <div style={{...detailsStyle,opacity:.65,fontSize:11,fontWeight:900}}>{label} · {tier} 🔒</div>}
function CoachLines({lines}:{lines:string[]}){return <div style={{display:'grid',gap:7,marginTop:9}}>{lines.map((line,i)=><div key={i} style={evidenceLine}><span>•</span><span>{line}</span></div>)}</div>}
function Evidence({label,value}:{label:string;value:string}){return <div style={{padding:'10px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><small className="muted">{label}</small><b style={{display:'block',marginTop:3}}>{value}</b></div>}
function Mini({label,value}:{label:string;value:string}){return <div style={{padding:'11px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><small className="muted">{label}</small><b style={{display:'block',marginTop:4}}>{value}</b></div>}
function MiniBlock({label,text}:{label:string;text:string}){return <div style={{padding:'12px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><div className="eyebrow">{label}</div><div style={{fontSize:12,lineHeight:1.5,marginTop:5}}>{text}</div></div>}
function SeverityPill({severity}:{severity:Severity}){return <span style={{...pill,fontSize:9}}>{severity}</span>}
function DataPill({status}:{status:string}){return <span style={{...pill,fontSize:8,opacity:.75}}>{status}</span>}
function GradePart({label,score}:{label:string;score:number}){return <div style={{padding:'10px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><small className="muted">{label}</small><b style={{display:'block',fontSize:18,marginTop:3}}>{score}</b></div>}
function TierPill({tier}:{tier:SubscriptionTier}){return <span style={{...pill,fontWeight:900}}>{tier}</span>}
function severityFor(n:number):Severity{return n>=4?'CRITICAL LEAK':n>=3?'MAJOR LEAK':n>=2?'ACTIVE LEAK':'POLISH'}function gradeBand(n:number):GradeBand{return n<40?'BROKEN':n<55?'EXPOSED':n<70?'STABLE':n<85?'SHARP':'OVERPOWERED'}function clamp(n:number){return Math.max(0,Math.min(100,Math.round(n)))}function pct(a:number,b:number){return b?Math.round(a/b*100):0}function signed(n:number){return`${n>0?'+':''}${Math.round(n*10)/10}`}function signedGold(n:number){return`${n>0?'+':''}${Math.round(n)}g`}function pctValue(n:number|null){return n===null?'Not exposed':`${Math.round(n*100)}%`}function formatClock(seconds:number){const s=Math.max(0,Math.floor(seconds));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}function verdictLabel(v:FightReview['verdict']){return v==='YOU_STRONGER'?'YOU WERE VISIBLY STRONGER':v==='THEM_STRONGER'?'THEY WERE VISIBLY STRONGER':'VISIBLE POWER WAS CLOSE'}
function tabStyle(active:boolean,type:'strength'|'weakness'):React.CSSProperties{return{display:'grid',gap:4,padding:15,borderRadius:15,border:active?`1px solid ${type==='strength'?'rgba(90,255,160,.5)':'rgba(255,110,110,.5)'}`:'1px solid rgba(255,255,255,.1)',background:active?(type==='strength'?'rgba(90,255,160,.08)':'rgba(255,110,110,.08)'):'transparent',color:'inherit',textAlign:'left',cursor:'pointer'}}
const topRow:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'};const rowShell:React.CSSProperties={border:'1px solid rgba(255,255,255,.1)',borderRadius:15,overflow:'hidden',background:'rgba(255,255,255,.025)'};const rowButton:React.CSSProperties={width:'100%',display:'grid',gridTemplateColumns:'48px minmax(0,1fr) auto',gap:12,alignItems:'center',padding:'14px 15px',border:0,background:'transparent',color:'inherit',textAlign:'left',cursor:'pointer'};const detailBody:React.CSSProperties={padding:'14px 15px 16px',borderTop:'1px solid rgba(255,255,255,.08)'};const detailsStyle:React.CSSProperties={marginTop:10,padding:'10px 12px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12,background:'rgba(255,255,255,.02)'};const summaryStyle:React.CSSProperties={cursor:'pointer',fontSize:11,fontWeight:900,letterSpacing:'.08em'};const pill:React.CSSProperties={padding:'5px 8px',borderRadius:999,border:'1px solid rgba(255,255,255,.1)',fontSize:9,letterSpacing:'.06em'};const emptyStyle:React.CSSProperties={padding:14,border:'1px solid rgba(255,255,255,.08)',borderRadius:13};const evidenceLine:React.CSSProperties={display:'grid',gridTemplateColumns:'auto minmax(0,1fr)',gap:8,fontSize:12,lineHeight:1.45};
