'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useAccount,matchesFor} from './AccountContext';
import {useLearningPlan} from './LearningPlanContext';
import {PageHead} from './UI';
import {WindowsTrackerInstaller} from './WindowsTrackerInstaller';
import {coachingLevelFor} from '@/lib/coachingLevel';
import {missionEvidence} from '@/lib/missionLoop';
import {readClimbSession,sessionGames as gamesInSession,type ClimbSessionState} from '@/lib/climbSession';
import {track} from '@/lib/analytics';
import {MissionMeasurementBadge} from './MissionMeasurementBadge';

type Device={id:string;account_key:string;device_name:string;created_at:string;last_seen_at:string|null};type Item={itemId:number;displayName:string;count:number;price:number};type Player={summonerName:string;riotId:string|null;championName:string;team:string;level:number;position:string|null;itemGold:number;items:Item[];scores:{kills:number;deaths:number;assists:number;creepScore:number;wardScore:number}};type Snapshot={gameTime:number;active:{summonerName:string;riotId:string|null;championName:string;position:string|null;currentGold:number};players:Player[]};type Review={matchId?:string|null;status:string;lastSeenAt:string|null;snapshotCount:number;latestSnapshot:Snapshot|null};
export function LiveCommandCenter(){const {active,isOwnAccount,profile,hydrated,refresh:refreshAccount}=useAccount();const {tasks}=useLearningPlan();const detail=coachingLevelFor(active.rank);const [devices,setDevices]=useState<Device[]>([]);const [devicesLoaded,setDevicesLoaded]=useState(false);const [review,setReview]=useState<Review|null>(null);const [pairCode,setPairCode]=useState('');const [pairExpiresAt,setPairExpiresAt]=useState('');const [pairStartedAt,setPairStartedAt]=useState(0);const [deviceName,setDeviceName]=useState('My Windows PC');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [session,setSession]=useState<ClimbSessionState|null>(null);const autoPairStarted=useRef(false);const connectedTracked=useRef(false);const recordingTracked=useRef(false);const completedReviewTracked=useRef('');
const refreshDevices=useCallback(async()=>{try{const response=await fetch('/api/live/pair',{cache:'no-store'});if(!response.ok)return;const body=await response.json();setDevices((body.devices??[]).filter((x:Device)=>x.account_key===active.id))}catch{}finally{setDevicesLoaded(true)}},[active.id]);const refreshReview=useCallback(async()=>{try{const response=await fetch(`/api/live/telemetry?accountId=${encodeURIComponent(active.id)}`,{cache:'no-store'});if(!response.ok)return;const body=await response.json();setReview(body.review??null)}catch{}},[active.id]);const refresh=useCallback(async()=>{await Promise.all([refreshDevices(),refreshReview()])},[refreshDevices,refreshReview]);
useEffect(()=>{connectedTracked.current=false;recordingTracked.current=false;completedReviewTracked.current='';setSession(readClimbSession(active.id));const sync=()=>setSession(readClimbSession(active.id));window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[active.id]);useEffect(()=>{setDevicesLoaded(false);autoPairStarted.current=false;void refresh();const reviewTick=()=>{if(document.visibilityState==='visible'){void refreshReview();setSession(readClimbSession(active.id))}};const deviceTick=()=>{if(document.visibilityState==='visible')void refreshDevices()};const onVisibility=()=>{if(document.visibilityState==='visible')void refresh()};const reviewId=window.setInterval(reviewTick,10_000);const deviceId=window.setInterval(deviceTick,15_000);document.addEventListener('visibilitychange',onVisibility);return()=>{window.clearInterval(reviewId);window.clearInterval(deviceId);document.removeEventListener('visibilitychange',onVisibility)}},[active.id,refresh,refreshDevices,refreshReview]);
useEffect(()=>{if(!pairCode)return;const tick=()=>{if(pairExpiresAt&&Date.now()>=new Date(pairExpiresAt).getTime()){setPairCode('');setPairExpiresAt('');setPairStartedAt(0);setMessage('That pairing link expired. Choose Connect installed Companion to create a fresh one.');return}void refreshDevices()};tick();const id=window.setInterval(tick,3_000);return()=>window.clearInterval(id)},[pairCode,pairExpiresAt,refreshDevices]);useEffect(()=>{if(!pairCode||!pairStartedAt)return;const newPcOnline=devices.some(device=>{const createdAt=new Date(device.created_at).getTime();return Number.isFinite(createdAt)&&createdAt>=pairStartedAt-5_000&&recent(device.last_seen_at,45_000)});if(newPcOnline){setPairCode('');setPairExpiresAt('');setPairStartedAt(0);setMessage('Companion heartbeat confirmed. This PC is connected and ready for League.')}},[devices,pairStartedAt,pairCode]);
const linked=devices.length>0,online=devices.some(device=>recent(device.last_seen_at,45_000)),snapshot=review?.latestSnapshot??null,me=useMemo(()=>snapshot?findMe(snapshot):null,[snapshot]),ready=Boolean(review&&['COMPLETE','ABORTED'].includes(review.status)&&snapshot),recording=Boolean(review?.status==='ACTIVE'&&recent(review.lastSeenAt,30_000)),staleActive=Boolean(review?.status==='ACTIVE'&&!recent(review.lastSeenAt,30_000)),status=recording?'RECORDING':staleActive?'GAME DATA LOST':online?'READY FOR LEAGUE':linked?'COMPANION OFFLINE':'SETUP REQUIRED',csMin=me&&snapshot?((me.scores.creepScore/Math.max(snapshot.gameTime/60,1/60))).toFixed(1):'—';
useEffect(()=>{if(online&&!connectedTracked.current){connectedTracked.current=true;track('companion_connected',{accountId:active.id,deviceCount:devices.length})}},[online,active.id,devices.length]);
useEffect(()=>{if(recording&&!recordingTracked.current){recordingTracked.current=true;track('companion_recording_started',{accountId:active.id,sessionActive:Boolean(session)})}else if(!recording){recordingTracked.current=false}},[recording,active.id,session]);
useEffect(()=>{if(review?.status!=='COMPLETE')return;const signature=String(review.lastSeenAt||review.snapshotCount||'complete');if(completedReviewTracked.current===signature)return;completedReviewTracked.current=signature;track('companion_game_completed',{accountId:active.id,snapshotCount:review.snapshotCount,sessionActive:Boolean(session)});void refreshAccount()},[review?.status,review?.lastSeenAt,review?.snapshotCount,active.id,session,refreshAccount]);
const accountMatches=matchesFor(active.id);const climbGames=session?gamesInSession(session,accountMatches):[];const sessionTask=session?tasks.find(task=>task.id===session.taskId):undefined;const activeMissions=tasks.filter(task=>task.status!=='MASTERED'&&task.status!=='PAUSED');const trackingMissions=[...(sessionTask?[sessionTask]:[]),...activeMissions.filter(task=>task.id!==sessionTask?.id)].slice(0,3);const nextGame=Math.min((climbGames.length+1),session?.targetGames||3);const latestSessionGame=climbGames.at(-1);const latestEvidence=sessionTask&&latestSessionGame?missionEvidence(sessionTask,latestSessionGame,active.rank):null;
async function pair(source:'manual'|'auto'='manual'){if(!isOwnAccount){setMessage('Switch to your own Riot account before pairing.');return}const startedAt=Date.now();track('companion_pair_started',{accountId:active.id,source});setBusy(true);setMessage('');setPairCode('');setPairExpiresAt('');setPairStartedAt(startedAt);try{const res=await fetch('/api/live/pair/code',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({accountId:active.id,deviceName,riotProfile:{gameName:active.gameName,tagline:active.tagline,region:active.region,role:active.role,rank:active.rank,champions:active.champions??[],frustration:profile?.frustration??''}})});const body=await res.json();if(!res.ok){setPairStartedAt(0);setMessage(body.error||'Pairing failed.');return}setPairCode(body.code||'');setPairExpiresAt(body.expiresAt||'');setMessage('Secure pairing ready. If the Companion is already installed, use Open Companion & Connect below — no reinstall is needed.')}catch{setPairStartedAt(0);setMessage('Could not reach the pairing service.')}finally{setBusy(false)}}
useEffect(()=>{if(!hydrated||!devicesLoaded||!isOwnAccount||online||pairCode||busy||autoPairStarted.current)return;autoPairStarted.current=true;setMessage('Installed Companion detected. Creating a secure one-time pairing…');void pair('auto')},[hydrated,devicesLoaded,isOwnAccount,online,pairCode,busy,active.id]);
return <div className="op-live-command"><PageHead title="Live Companion" subtitle={session?`CLIMB SESSION · GAME ${nextGame}/${session.targetGames} · One focus, recorded quietly.`:`${detail.tier} VIEW ${detail.depth}/10 · Record quietly. Review after the game.`}/>
{session&&<section className="hq-command" style={{marginBottom:18}}><div className="hq-top"><span className="v7-badge engine">CLIMB SESSION</span><span className="v7-badge">GAME {nextGame}/{session.targetGames}</span></div>{recording||staleActive?<><div className="eyebrow">MISSIONS LOCKED BEFORE THE GAME</div><h2>TRACKING ONLY</h2><p>OP CLIMB is measuring the goals you entered the match with. It will not add tactical instructions while the game is running.</p><div className="op-live-mission-grid">{trackingMissions.length?trackingMissions.map((mission,index)=><div className="glass card op-live-mission" key={mission.id}><span>{index===0?'CORE MISSION':'SUPPORT 0'+index}</span><b>{mission.title}</b><MissionMeasurementBadge metric={mission.metric} compact/><small>TARGET · {mission.target}</small><em>{staleActive?'WAITING FOR GAME DATA':'EVIDENCE RECORDING'}</em></div>):<div className="glass card op-live-mission"><span>MISSION TRACKING</span><b>{session.taskTitle}</b><small>TARGET · {session.target}</small><em>{staleActive?'WAITING FOR GAME DATA':'EVIDENCE RECORDING'}</em></div>}</div></>:<><h2>{session.taskTitle}</h2><p>{sessionTask?.why||'This is the behaviour your development plan has chosen to train.'}</p><div className="hq-rules"><div><span className="label">PRE-GAME PLAN</span><b>{session.gameRule}</b></div><div><span className="label">MISSION BAR</span><b>{session.target}</b></div></div></>}{!recording&&!staleActive&&latestSessionGame&&<div className="glass card" style={{marginTop:14}}><div className="eyebrow">GAME {climbGames.length} REVIEW</div><h3>{latestSessionGame.result} · {latestSessionGame.champion} · {latestSessionGame.kills}/{latestSessionGame.deaths}/{latestSessionGame.assists}</h3><b>{latestEvidence?.available?(latestEvidence.clearedBar?'MISSION BAR CLEARED ✓':'KEEP WORKING'):'EVIDENCE BUILDING'}</b><p className="muted">{latestEvidence?.reason}</p><Link className="text-link" href={`/analyse/${encodeURIComponent(latestSessionGame.id)}`}>OPEN FULL REVIEW →</Link></div>}<div className="hero-actions"><Link className="btn secondary" href="/session">OPEN SESSION REVIEW →</Link></div></section>}
<section className={`glass card op-live-status ${recording?'is-recording':staleActive?'is-stale':online?'is-ready':''}`}><div className="op-live-status-copy"><div><div className="eyebrow">OP CLIMB COMPANION · {detail.tier}</div><h2>{status}</h2><p className="muted">{recording?'Tracking is healthy. No live tactical advice is shown — coaching resumes after the match.':staleActive?'The match was detected, but fresh telemetry has stopped. OP CLIMB is reconnecting and will not treat stale data as live evidence.':online?(session?`Ready for Climb Session game ${nextGame}. Your pre-game missions are locked.`:'Companion is ready. Leave it quietly in your Windows tray and play normally.'):linked?'Your PC is registered, but the Companion is offline. Open the installed Companion and reconnect below.':'Connect the Windows Companion once, then OP CLIMB can record your League matches.'}</p></div><span className="op-live-status-pill">{recording?'● TRACKING':staleActive?'⚠ RECONNECTING':online?'● ONLINE':linked?'○ OFFLINE':'SETUP'}</span></div>{recording&&snapshot&&<div className="grid three op-live-recording"><Mini label="CHAMPION" value={snapshot.active.championName||'Detecting'}/>{detail.depth>=2&&<Mini label="GAME TIME" value={clock(snapshot.gameTime)}/>} {detail.depth>=5&&<Mini label="CAPTURE POINTS" value={String(review?.snapshotCount??0)}/>}</div>}</section>
{ready&&snapshot&&me&&<section className="op-latest-match"><div className="glass card op-match-card"><div className="op-match-head"><div><div className="eyebrow">LATEST MATCH · {detail.tier} DETAIL</div><h2>{me.championName}{detail.depth>=2&&<span> · {role(snapshot.active.position)}</span>}</h2></div>{detail.depth>=3&&<b>{clock(snapshot.gameTime)}</b>}</div><div className="grid three op-match-metrics"><Mini label="K / D / A" value={`${me.scores.kills} / ${me.scores.deaths} / ${me.scores.assists}`}/>{detail.depth>=2&&<Mini label="CS / MIN" value={csMin}/>} {detail.depth>=3&&<Mini label="LEVEL" value={String(me.level)}/>}</div><div className="op-next-read"><div className="eyebrow">WHAT MATTERS NEXT</div><b>{session?'Return to the same session focus — do not add another lesson.':'OP Grade → Core + 2 Support → Match Review → Evidence'}</b></div>{review?.matchId&&<div className="hero-actions" style={{marginTop:14}}><Link className="btn primary" href={'/analyse/'+encodeURIComponent(review.matchId)}>OPEN FULL MATCH REVIEW →</Link></div>}</div></section>}
<details className="glass card op-quiet-details op-tracker-setup" open={!online||Boolean(pairCode)}><summary>{online?'COMPANION SETUP & DEVICES':linked?'COMPANION OFFLINE — RECONNECT':'CONNECT THIS WINDOWS PC'}</summary><div style={{marginTop:16}}><p className="muted">Already installed? Connect it directly below. Only download the installer if this PC does not have OP CLIMB Companion yet.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'end'}}><label style={{display:'grid',gap:6,minWidth:220}}><span className="muted">Device name</span><input value={deviceName} onChange={e=>setDeviceName(e.target.value)} maxLength={80} style={{padding:'12px 14px',borderRadius:12}}/></label><button className="btn primary" type="button" disabled={busy||!isOwnAccount} onClick={()=>void pair()}>{busy?'CREATING SECURE PAIRING…':online?'PAIR ANOTHER PC':'CONNECT INSTALLED COMPANION'}</button><a className="btn" href="/download/windows" target="_blank" rel="noopener">DOWNLOAD COMPANION</a></div>{message&&<p style={{marginTop:12}}>{message}</p>}{pairCode&&<WindowsTrackerInstaller code={pairCode}/>}</div></details></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="glass op-live-metric"><div className="eyebrow">{label}</div><strong>{value}</strong></div>}function findMe(s:Snapshot){return s.players.find(p=>Boolean(s.active.riotId&&p.riotId===s.active.riotId))||s.players.find(p=>p.summonerName===s.active.summonerName)||s.players.find(p=>p.championName===s.active.championName)||null}function role(v:string|null){const x=(v||'').toUpperCase();return x==='BOTTOM'?'ADC':x||'ROLE UNKNOWN'}function clock(sec:number){const n=Math.max(0,Math.round(sec));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}function recent(value:string|null,ms:number){if(!value)return false;return Date.now()-new Date(value).getTime()<=ms}
