import 'server-only';

export type LearningMemory={id:string;kind:string;topic:string;summary:string;metric:string|null;firstSeenAt:string;lastSeenAt:string;occurrences:number;status:string;evidence:any[]};

export async function createPersistentClimbSession(db:any,userId:string,accountId:string,mission:any){
 const {data,error}=await db.from('op_climb_sessions').insert({user_id:userId,riot_account_id:accountId,mission_id:String(mission.id),mission_title:String(mission.title),mission_metric:String(mission.metric),game_rule:String(mission.gameRule),target:String(mission.target),status:'ACTIVE',target_games:3}).select('id,user_id,riot_account_id,mission_id,mission_title,mission_metric,game_rule,target,status,target_games,started_at').single();
 if(error)throw new Error(error.message);return data;
}
export async function getActiveClimbSession(db:any,userId:string,accountId:string){const {data,error}=await db.from('op_climb_sessions').select('*').eq('user_id',userId).eq('riot_account_id',accountId).eq('status','ACTIVE').order('started_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data??null}
export async function getSessionGames(db:any,userId:string,sessionId:string){const {data,error}=await db.from('op_climb_session_games').select('*').eq('user_id',userId).eq('session_id',sessionId).order('game_number',{ascending:true});if(error)throw new Error(error.message);return data??[]}
export async function attachSessionGame(db:any,input:{userId:string;sessionId:string;matchId?:string|null;telemetrySessionId?:string|null;gameNumber:number;result?:string|null;evidence?:any}){const {data,error}=await db.from('op_climb_session_games').upsert({user_id:input.userId,session_id:input.sessionId,match_id:input.matchId??null,telemetry_session_id:input.telemetrySessionId??null,game_number:input.gameNumber,result:input.result??null,evidence:input.evidence??{}},{onConflict:'session_id,game_number'}).select('*').single();if(error)throw new Error(error.message);return data}
export async function completeClimbSession(db:any,userId:string,sessionId:string,verdict:any={}){const {error}=await db.from('op_climb_sessions').update({status:'COMPLETE',completed_at:new Date().toISOString(),verdict}).eq('id',sessionId).eq('user_id',userId);if(error)throw new Error(error.message)}

export async function rememberPlayerStatement(db:any,userId:string,accountId:string,message:string){const topic=detectTopic(message);if(!topic)return null;const now=new Date().toISOString();const {data:existing,error}=await db.from('op_coach_memories').select('*').eq('user_id',userId).eq('riot_account_id',accountId).eq('kind','PLAYER_STATEMENT').eq('topic',topic.topic).eq('status','ACTIVE').order('last_seen_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);const evidence=[...((existing?.evidence as any[])??[]),{at:now,source:'coach',text:message.slice(0,500)}].slice(-8);const row={user_id:userId,riot_account_id:accountId,kind:'PLAYER_STATEMENT',topic:topic.topic,summary:topic.summary,metric:topic.metric,first_seen_at:existing?.first_seen_at??now,last_seen_at:now,occurrences:Number(existing?.occurrences??0)+1,status:'ACTIVE',evidence};const query=existing?.id?db.from('op_coach_memories').update(row).eq('id',existing.id):db.from('op_coach_memories').insert(row);const {data,error:saveError}=await query.select('*').single();if(saveError)throw new Error(saveError.message);return data}
export async function loadCoachMemories(db:any,userId:string,accountId:string,limit=8):Promise<LearningMemory[]>{const {data,error}=await db.from('op_coach_memories').select('id,kind,topic,summary,metric,first_seen_at,last_seen_at,occurrences,status,evidence').eq('user_id',userId).eq('riot_account_id',accountId).eq('status','ACTIVE').order('last_seen_at',{ascending:false}).limit(limit);if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({id:x.id,kind:x.kind,topic:x.topic,summary:x.summary,metric:x.metric,firstSeenAt:x.first_seen_at,lastSeenAt:x.last_seen_at,occurrences:Number(x.occurrences||1),status:x.status,evidence:x.evidence??[]}))}

function detectTopic(message:string){const m=message.toLowerCase();const rules=[[/panic|panicking|tilt|tilted|frustrat|angry|raging/,'playing_under_pressure','Player reports emotional or decision pressure affecting play.','red_state_fights'],[/fight|engag|go in|dive|overextend/,'fight_selection','Player reports uncertainty or mistakes around choosing fights.','fight_selection'],[/die|dying|death|caught/,'death_control','Player reports avoidable deaths or getting caught.','death_control'],[/farm|cs|creep/,'resource_collection','Player reports farming or resource collection difficulty.','cs_curve'],[/reset|recall|back timing/,'reset_timing','Player reports reset or recall timing difficulty.','reset_quality'],[/objective|dragon|baron|grub|herald/,'objective_readiness','Player reports objective setup or timing difficulty.','objective_readiness'],[/lead|throw|ahead/,'lead_protection','Player reports difficulty converting or protecting a lead.','lead_protection']];for(const [re,topic,summary,metric] of rules as any[])if(re.test(m))return{topic,summary,metric};return null}
