import 'server-only';

export type LearningMemory={id:string;kind:string;topic:string;summary:string;metric:string|null;firstSeenAt:string;lastSeenAt:string;occurrences:number;status:string;evidence:any[]};

export async function createPersistentClimbSession(db:any,userId:string,accountId:string,mission:any){
 const missionSnapshot={id:String(mission.id),title:String(mission.title),metric:String(mission.metric),gameRule:String(mission.gameRule),target:String(mission.target),why:String(mission.why||''),priority:Number(mission.priority||0)};
 const {data,error}=await db.from('op_climb_sessions').insert({user_id:userId,riot_account_id:accountId,mission_id:missionSnapshot.id,mission_snapshot:missionSnapshot,status:'ACTIVE',target_games:3}).select('*').single();
 if(error)throw new Error(error.message);return data;
}
export async function getActiveClimbSession(db:any,userId:string,accountId:string){const {data,error}=await db.from('op_climb_sessions').select('*').eq('user_id',userId).eq('riot_account_id',accountId).eq('status','ACTIVE').order('started_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data??null}
export async function getSessionGames(db:any,userId:string,sessionId:string){const {data,error}=await db.from('op_climb_session_games').select('*').eq('user_id',userId).eq('session_id',sessionId).order('game_number',{ascending:true});if(error)throw new Error(error.message);return data??[]}
export async function attachSessionGame(db:any,input:{userId:string;accountId:string;sessionId:string;matchId?:string|null;externalMatchId?:string|null;telemetrySessionId?:string|null;gameNumber:number;missionResult?:any}){const {data,error}=await db.from('op_climb_session_games').upsert({user_id:input.userId,riot_account_id:input.accountId,session_id:input.sessionId,match_id:input.matchId??null,external_match_id:input.externalMatchId??null,telemetry_session_id:input.telemetrySessionId??null,game_number:input.gameNumber,mission_result:input.missionResult??{}},{onConflict:'session_id,game_number'}).select('*').single();if(error)throw new Error(error.message);return data}
export async function completeClimbSession(db:any,userId:string,sessionId:string){const {error}=await db.from('op_climb_sessions').update({status:'COMPLETE',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',sessionId).eq('user_id',userId);if(error)throw new Error(error.message)}

export async function recordCompletedClimbSessionGame(db:any,input:{userId:string;accountId:string|null;telemetrySessionId:string}){
 if(!input.accountId)return null;
 const session=await getActiveClimbSession(db,input.userId,input.accountId);if(!session)return null;
 const {data:duplicate,error:duplicateError}=await db.from('op_climb_session_games').select('id,game_number').eq('session_id',session.id).eq('telemetry_session_id',input.telemetrySessionId).maybeSingle();if(duplicateError)throw new Error(duplicateError.message);if(duplicate)return duplicate;
 const games=await getSessionGames(db,input.userId,session.id);const gameNumber=games.length+1;if(gameNumber>Number(session.target_games||3))return null;
 const [{data:match,error:matchError},{data:pro,error:proError}]=await Promise.all([db.from('matches').select('id,external_match_id,result,champion,role,kills,deaths,assists').eq('user_id',input.userId).eq('riot_account_id',input.accountId).eq('live_session_id',input.telemetrySessionId).maybeSingle(),db.from('op_match_analysis').select('analysis').eq('user_id',input.userId).eq('riot_account_id',input.accountId).eq('session_id',input.telemetrySessionId).maybeSingle()]);
 if(matchError)throw new Error(matchError.message);if(proError)throw new Error(proError.message);
 const metric=String(session.mission_snapshot?.metric||'');const measured=metric&&pro?.analysis?.metrics?.[metric]?pro.analysis.metrics[metric]:null;
 const missionResult={result:match?.result??null,champion:match?.champion??null,role:match?.role??null,kda:match?{kills:match.kills,deaths:match.deaths,assists:match.assists}:null,metric,measured:measured?{score:measured.score,status:measured.status,confidence:measured.confidence,summary:measured.summary}:null,recordedAt:new Date().toISOString()};
 const attached=await attachSessionGame(db,{userId:input.userId,accountId:input.accountId,sessionId:session.id,matchId:match?.id??null,externalMatchId:match?.external_match_id??null,telemetrySessionId:input.telemetrySessionId,gameNumber,missionResult});
 if(gameNumber>=Number(session.target_games||3))await completeClimbSession(db,input.userId,session.id);
 return attached;
}

export async function rememberPlayerStatement(db:any,userId:string,accountId:string,message:string){const topic=detectTopic(message);if(!topic)return null;const now=new Date().toISOString(),memoryKey=`player-stated:${topic.topic}`;const {data:existing,error}=await db.from('op_coach_memories').select('*').eq('user_id',userId).eq('riot_account_id',accountId).eq('memory_key',memoryKey).maybeSingle();if(error)throw new Error(error.message);const evidence=[...((existing?.evidence as any[])??[]),{at:now,source:'coach',metric:topic.metric,text:message.slice(0,500)}].slice(-8);const row={user_id:userId,riot_account_id:accountId,memory_key:memoryKey,memory_type:'PLAYER_STATED',topic:topic.topic,summary:topic.summary,evidence,first_seen_at:existing?.first_seen_at??now,last_seen_at:now,occurrences:Number(existing?.occurrences??0)+1,status:'ACTIVE',updated_at:now};const {data,error:saveError}=await db.from('op_coach_memories').upsert(row,{onConflict:'user_id,riot_account_id,memory_key'}).select('*').single();if(saveError)throw new Error(saveError.message);return data}
export async function loadCoachMemories(db:any,userId:string,accountId:string,limit=8):Promise<LearningMemory[]>{const {data,error}=await db.from('op_coach_memories').select('id,memory_type,topic,summary,first_seen_at,last_seen_at,occurrences,status,evidence').eq('user_id',userId).eq('riot_account_id',accountId).in('status',['ACTIVE','IMPROVING']).order('last_seen_at',{ascending:false}).limit(limit);if(error)throw new Error(error.message);return(data??[]).map((x:any)=>{const evidence=Array.isArray(x.evidence)?x.evidence:[];const metric=evidence.slice().reverse().find((item:any)=>item?.metric)?.metric??null;return{id:x.id,kind:x.memory_type,topic:x.topic,summary:x.summary,metric,firstSeenAt:x.first_seen_at,lastSeenAt:x.last_seen_at,occurrences:Number(x.occurrences||1),status:x.status,evidence}})}

function detectTopic(message:string){const m=message.toLowerCase();const rules=[[/panic|panicking|tilt|tilted|frustrat|angry|raging/,'playing_under_pressure','Player reports emotional or decision pressure affecting play.','red_state_fights'],[/fight|engag|go in|dive|overextend/,'fight_selection','Player reports uncertainty or mistakes around choosing fights.','fight_selection'],[/die|dying|death|caught/,'death_control','Player reports avoidable deaths or getting caught.','death_control'],[/farm|cs|creep/,'resource_collection','Player reports farming or resource collection difficulty.','cs_curve'],[/reset|recall|back timing/,'reset_timing','Player reports reset or recall timing difficulty.','reset_quality'],[/objective|dragon|baron|grub|herald/,'objective_readiness','Player reports objective setup or timing difficulty.','objective_readiness'],[/lead|throw|ahead/,'lead_protection','Player reports difficulty converting or protecting a lead.','lead_protection']];for(const [re,topic,summary,metric] of rules as any[])if(re.test(m))return{topic,summary,metric};return null}
